
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Applications` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Applications
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type ApplicationsModel = runtime.Types.Result.DefaultSelection<Prisma.$ApplicationsPayload>

export type AggregateApplications = {
  _count: ApplicationsCountAggregateOutputType | null
  _avg: ApplicationsAvgAggregateOutputType | null
  _sum: ApplicationsSumAggregateOutputType | null
  _min: ApplicationsMinAggregateOutputType | null
  _max: ApplicationsMaxAggregateOutputType | null
}

export type ApplicationsAvgAggregateOutputType = {
  id: number | null
  job_id: number | null
}

export type ApplicationsSumAggregateOutputType = {
  id: number | null
  job_id: number | null
}

export type ApplicationsMinAggregateOutputType = {
  id: number | null
  user_id: string | null
  job_id: number | null
  status: $Enums.ApplicationStatus | null
}

export type ApplicationsMaxAggregateOutputType = {
  id: number | null
  user_id: string | null
  job_id: number | null
  status: $Enums.ApplicationStatus | null
}

export type ApplicationsCountAggregateOutputType = {
  id: number
  user_id: number
  job_id: number
  status: number
  _all: number
}


export type ApplicationsAvgAggregateInputType = {
  id?: true
  job_id?: true
}

export type ApplicationsSumAggregateInputType = {
  id?: true
  job_id?: true
}

export type ApplicationsMinAggregateInputType = {
  id?: true
  user_id?: true
  job_id?: true
  status?: true
}

export type ApplicationsMaxAggregateInputType = {
  id?: true
  user_id?: true
  job_id?: true
  status?: true
}

export type ApplicationsCountAggregateInputType = {
  id?: true
  user_id?: true
  job_id?: true
  status?: true
  _all?: true
}

export type ApplicationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Applications to aggregate.
   */
  where?: Prisma.ApplicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationsOrderByWithRelationInput | Prisma.ApplicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApplicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Applications
  **/
  _count?: true | ApplicationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApplicationsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApplicationsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApplicationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApplicationsMaxAggregateInputType
}

export type GetApplicationsAggregateType<T extends ApplicationsAggregateArgs> = {
      [P in keyof T & keyof AggregateApplications]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApplications[P]>
    : Prisma.GetScalarType<T[P], AggregateApplications[P]>
}




export type ApplicationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationsWhereInput
  orderBy?: Prisma.ApplicationsOrderByWithAggregationInput | Prisma.ApplicationsOrderByWithAggregationInput[]
  by: Prisma.ApplicationsScalarFieldEnum[] | Prisma.ApplicationsScalarFieldEnum
  having?: Prisma.ApplicationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApplicationsCountAggregateInputType | true
  _avg?: ApplicationsAvgAggregateInputType
  _sum?: ApplicationsSumAggregateInputType
  _min?: ApplicationsMinAggregateInputType
  _max?: ApplicationsMaxAggregateInputType
}

export type ApplicationsGroupByOutputType = {
  id: number
  user_id: string | null
  job_id: number | null
  status: $Enums.ApplicationStatus | null
  _count: ApplicationsCountAggregateOutputType | null
  _avg: ApplicationsAvgAggregateOutputType | null
  _sum: ApplicationsSumAggregateOutputType | null
  _min: ApplicationsMinAggregateOutputType | null
  _max: ApplicationsMaxAggregateOutputType | null
}

type GetApplicationsGroupByPayload<T extends ApplicationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApplicationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApplicationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApplicationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApplicationsGroupByOutputType[P]>
      }
    >
  >



export type ApplicationsWhereInput = {
  AND?: Prisma.ApplicationsWhereInput | Prisma.ApplicationsWhereInput[]
  OR?: Prisma.ApplicationsWhereInput[]
  NOT?: Prisma.ApplicationsWhereInput | Prisma.ApplicationsWhereInput[]
  id?: Prisma.IntFilter<"Applications"> | number
  user_id?: Prisma.UuidNullableFilter<"Applications"> | string | null
  job_id?: Prisma.IntNullableFilter<"Applications"> | number | null
  status?: Prisma.EnumApplicationStatusNullableFilter<"Applications"> | $Enums.ApplicationStatus | null
  jobs?: Prisma.XOR<Prisma.JobsNullableScalarRelationFilter, Prisma.JobsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.UsersWhereInput> | null
}

export type ApplicationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  job_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  jobs?: Prisma.JobsOrderByWithRelationInput
  users?: Prisma.UsersOrderByWithRelationInput
}

export type ApplicationsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ApplicationsWhereInput | Prisma.ApplicationsWhereInput[]
  OR?: Prisma.ApplicationsWhereInput[]
  NOT?: Prisma.ApplicationsWhereInput | Prisma.ApplicationsWhereInput[]
  user_id?: Prisma.UuidNullableFilter<"Applications"> | string | null
  job_id?: Prisma.IntNullableFilter<"Applications"> | number | null
  status?: Prisma.EnumApplicationStatusNullableFilter<"Applications"> | $Enums.ApplicationStatus | null
  jobs?: Prisma.XOR<Prisma.JobsNullableScalarRelationFilter, Prisma.JobsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.UsersWhereInput> | null
}, "id">

export type ApplicationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  job_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ApplicationsCountOrderByAggregateInput
  _avg?: Prisma.ApplicationsAvgOrderByAggregateInput
  _max?: Prisma.ApplicationsMaxOrderByAggregateInput
  _min?: Prisma.ApplicationsMinOrderByAggregateInput
  _sum?: Prisma.ApplicationsSumOrderByAggregateInput
}

export type ApplicationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApplicationsScalarWhereWithAggregatesInput | Prisma.ApplicationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApplicationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApplicationsScalarWhereWithAggregatesInput | Prisma.ApplicationsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Applications"> | number
  user_id?: Prisma.UuidNullableWithAggregatesFilter<"Applications"> | string | null
  job_id?: Prisma.IntNullableWithAggregatesFilter<"Applications"> | number | null
  status?: Prisma.EnumApplicationStatusNullableWithAggregatesFilter<"Applications"> | $Enums.ApplicationStatus | null
}

export type ApplicationsCreateInput = {
  status?: $Enums.ApplicationStatus | null
  jobs?: Prisma.JobsCreateNestedOneWithoutApplicationsInput
  users?: Prisma.UsersCreateNestedOneWithoutApplicationsInput
}

export type ApplicationsUncheckedCreateInput = {
  id?: number
  user_id?: string | null
  job_id?: number | null
  status?: $Enums.ApplicationStatus | null
}

export type ApplicationsUpdateInput = {
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
  jobs?: Prisma.JobsUpdateOneWithoutApplicationsNestedInput
  users?: Prisma.UsersUpdateOneWithoutApplicationsNestedInput
}

export type ApplicationsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
}

export type ApplicationsCreateManyInput = {
  id?: number
  user_id?: string | null
  job_id?: number | null
  status?: $Enums.ApplicationStatus | null
}

export type ApplicationsUpdateManyMutationInput = {
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
}

export type ApplicationsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
}

export type ApplicationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ApplicationsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
}

export type ApplicationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ApplicationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ApplicationsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
}

export type ApplicationsListRelationFilter = {
  every?: Prisma.ApplicationsWhereInput
  some?: Prisma.ApplicationsWhereInput
  none?: Prisma.ApplicationsWhereInput
}

export type ApplicationsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableEnumApplicationStatusFieldUpdateOperationsInput = {
  set?: $Enums.ApplicationStatus | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ApplicationsCreateNestedManyWithoutJobsInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutJobsInput, Prisma.ApplicationsUncheckedCreateWithoutJobsInput> | Prisma.ApplicationsCreateWithoutJobsInput[] | Prisma.ApplicationsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutJobsInput | Prisma.ApplicationsCreateOrConnectWithoutJobsInput[]
  createMany?: Prisma.ApplicationsCreateManyJobsInputEnvelope
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
}

export type ApplicationsUncheckedCreateNestedManyWithoutJobsInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutJobsInput, Prisma.ApplicationsUncheckedCreateWithoutJobsInput> | Prisma.ApplicationsCreateWithoutJobsInput[] | Prisma.ApplicationsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutJobsInput | Prisma.ApplicationsCreateOrConnectWithoutJobsInput[]
  createMany?: Prisma.ApplicationsCreateManyJobsInputEnvelope
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
}

export type ApplicationsUpdateManyWithoutJobsNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutJobsInput, Prisma.ApplicationsUncheckedCreateWithoutJobsInput> | Prisma.ApplicationsCreateWithoutJobsInput[] | Prisma.ApplicationsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutJobsInput | Prisma.ApplicationsCreateOrConnectWithoutJobsInput[]
  upsert?: Prisma.ApplicationsUpsertWithWhereUniqueWithoutJobsInput | Prisma.ApplicationsUpsertWithWhereUniqueWithoutJobsInput[]
  createMany?: Prisma.ApplicationsCreateManyJobsInputEnvelope
  set?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  disconnect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  delete?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  update?: Prisma.ApplicationsUpdateWithWhereUniqueWithoutJobsInput | Prisma.ApplicationsUpdateWithWhereUniqueWithoutJobsInput[]
  updateMany?: Prisma.ApplicationsUpdateManyWithWhereWithoutJobsInput | Prisma.ApplicationsUpdateManyWithWhereWithoutJobsInput[]
  deleteMany?: Prisma.ApplicationsScalarWhereInput | Prisma.ApplicationsScalarWhereInput[]
}

export type ApplicationsUncheckedUpdateManyWithoutJobsNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutJobsInput, Prisma.ApplicationsUncheckedCreateWithoutJobsInput> | Prisma.ApplicationsCreateWithoutJobsInput[] | Prisma.ApplicationsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutJobsInput | Prisma.ApplicationsCreateOrConnectWithoutJobsInput[]
  upsert?: Prisma.ApplicationsUpsertWithWhereUniqueWithoutJobsInput | Prisma.ApplicationsUpsertWithWhereUniqueWithoutJobsInput[]
  createMany?: Prisma.ApplicationsCreateManyJobsInputEnvelope
  set?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  disconnect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  delete?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  update?: Prisma.ApplicationsUpdateWithWhereUniqueWithoutJobsInput | Prisma.ApplicationsUpdateWithWhereUniqueWithoutJobsInput[]
  updateMany?: Prisma.ApplicationsUpdateManyWithWhereWithoutJobsInput | Prisma.ApplicationsUpdateManyWithWhereWithoutJobsInput[]
  deleteMany?: Prisma.ApplicationsScalarWhereInput | Prisma.ApplicationsScalarWhereInput[]
}

export type ApplicationsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutUsersInput, Prisma.ApplicationsUncheckedCreateWithoutUsersInput> | Prisma.ApplicationsCreateWithoutUsersInput[] | Prisma.ApplicationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutUsersInput | Prisma.ApplicationsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.ApplicationsCreateManyUsersInputEnvelope
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
}

export type ApplicationsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutUsersInput, Prisma.ApplicationsUncheckedCreateWithoutUsersInput> | Prisma.ApplicationsCreateWithoutUsersInput[] | Prisma.ApplicationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutUsersInput | Prisma.ApplicationsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.ApplicationsCreateManyUsersInputEnvelope
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
}

export type ApplicationsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutUsersInput, Prisma.ApplicationsUncheckedCreateWithoutUsersInput> | Prisma.ApplicationsCreateWithoutUsersInput[] | Prisma.ApplicationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutUsersInput | Prisma.ApplicationsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ApplicationsUpsertWithWhereUniqueWithoutUsersInput | Prisma.ApplicationsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.ApplicationsCreateManyUsersInputEnvelope
  set?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  disconnect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  delete?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  update?: Prisma.ApplicationsUpdateWithWhereUniqueWithoutUsersInput | Prisma.ApplicationsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ApplicationsUpdateManyWithWhereWithoutUsersInput | Prisma.ApplicationsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ApplicationsScalarWhereInput | Prisma.ApplicationsScalarWhereInput[]
}

export type ApplicationsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationsCreateWithoutUsersInput, Prisma.ApplicationsUncheckedCreateWithoutUsersInput> | Prisma.ApplicationsCreateWithoutUsersInput[] | Prisma.ApplicationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ApplicationsCreateOrConnectWithoutUsersInput | Prisma.ApplicationsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ApplicationsUpsertWithWhereUniqueWithoutUsersInput | Prisma.ApplicationsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.ApplicationsCreateManyUsersInputEnvelope
  set?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  disconnect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  delete?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  connect?: Prisma.ApplicationsWhereUniqueInput | Prisma.ApplicationsWhereUniqueInput[]
  update?: Prisma.ApplicationsUpdateWithWhereUniqueWithoutUsersInput | Prisma.ApplicationsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ApplicationsUpdateManyWithWhereWithoutUsersInput | Prisma.ApplicationsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ApplicationsScalarWhereInput | Prisma.ApplicationsScalarWhereInput[]
}

export type ApplicationsCreateWithoutJobsInput = {
  status?: $Enums.ApplicationStatus | null
  users?: Prisma.UsersCreateNestedOneWithoutApplicationsInput
}

export type ApplicationsUncheckedCreateWithoutJobsInput = {
  id?: number
  user_id?: string | null
  status?: $Enums.ApplicationStatus | null
}

export type ApplicationsCreateOrConnectWithoutJobsInput = {
  where: Prisma.ApplicationsWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationsCreateWithoutJobsInput, Prisma.ApplicationsUncheckedCreateWithoutJobsInput>
}

export type ApplicationsCreateManyJobsInputEnvelope = {
  data: Prisma.ApplicationsCreateManyJobsInput | Prisma.ApplicationsCreateManyJobsInput[]
  skipDuplicates?: boolean
}

export type ApplicationsUpsertWithWhereUniqueWithoutJobsInput = {
  where: Prisma.ApplicationsWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationsUpdateWithoutJobsInput, Prisma.ApplicationsUncheckedUpdateWithoutJobsInput>
  create: Prisma.XOR<Prisma.ApplicationsCreateWithoutJobsInput, Prisma.ApplicationsUncheckedCreateWithoutJobsInput>
}

export type ApplicationsUpdateWithWhereUniqueWithoutJobsInput = {
  where: Prisma.ApplicationsWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationsUpdateWithoutJobsInput, Prisma.ApplicationsUncheckedUpdateWithoutJobsInput>
}

export type ApplicationsUpdateManyWithWhereWithoutJobsInput = {
  where: Prisma.ApplicationsScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationsUpdateManyMutationInput, Prisma.ApplicationsUncheckedUpdateManyWithoutJobsInput>
}

export type ApplicationsScalarWhereInput = {
  AND?: Prisma.ApplicationsScalarWhereInput | Prisma.ApplicationsScalarWhereInput[]
  OR?: Prisma.ApplicationsScalarWhereInput[]
  NOT?: Prisma.ApplicationsScalarWhereInput | Prisma.ApplicationsScalarWhereInput[]
  id?: Prisma.IntFilter<"Applications"> | number
  user_id?: Prisma.UuidNullableFilter<"Applications"> | string | null
  job_id?: Prisma.IntNullableFilter<"Applications"> | number | null
  status?: Prisma.EnumApplicationStatusNullableFilter<"Applications"> | $Enums.ApplicationStatus | null
}

export type ApplicationsCreateWithoutUsersInput = {
  status?: $Enums.ApplicationStatus | null
  jobs?: Prisma.JobsCreateNestedOneWithoutApplicationsInput
}

export type ApplicationsUncheckedCreateWithoutUsersInput = {
  id?: number
  job_id?: number | null
  status?: $Enums.ApplicationStatus | null
}

export type ApplicationsCreateOrConnectWithoutUsersInput = {
  where: Prisma.ApplicationsWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationsCreateWithoutUsersInput, Prisma.ApplicationsUncheckedCreateWithoutUsersInput>
}

export type ApplicationsCreateManyUsersInputEnvelope = {
  data: Prisma.ApplicationsCreateManyUsersInput | Prisma.ApplicationsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type ApplicationsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ApplicationsWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationsUpdateWithoutUsersInput, Prisma.ApplicationsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.ApplicationsCreateWithoutUsersInput, Prisma.ApplicationsUncheckedCreateWithoutUsersInput>
}

export type ApplicationsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ApplicationsWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationsUpdateWithoutUsersInput, Prisma.ApplicationsUncheckedUpdateWithoutUsersInput>
}

export type ApplicationsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.ApplicationsScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationsUpdateManyMutationInput, Prisma.ApplicationsUncheckedUpdateManyWithoutUsersInput>
}

export type ApplicationsCreateManyJobsInput = {
  id?: number
  user_id?: string | null
  status?: $Enums.ApplicationStatus | null
}

export type ApplicationsUpdateWithoutJobsInput = {
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
  users?: Prisma.UsersUpdateOneWithoutApplicationsNestedInput
}

export type ApplicationsUncheckedUpdateWithoutJobsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
}

export type ApplicationsUncheckedUpdateManyWithoutJobsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
}

export type ApplicationsCreateManyUsersInput = {
  id?: number
  job_id?: number | null
  status?: $Enums.ApplicationStatus | null
}

export type ApplicationsUpdateWithoutUsersInput = {
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
  jobs?: Prisma.JobsUpdateOneWithoutApplicationsNestedInput
}

export type ApplicationsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
}

export type ApplicationsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableEnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus | null
}



export type ApplicationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  status?: boolean
  jobs?: boolean | Prisma.Applications$jobsArgs<ExtArgs>
  users?: boolean | Prisma.Applications$usersArgs<ExtArgs>
}, ExtArgs["result"]["applications"]>

export type ApplicationsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  status?: boolean
  jobs?: boolean | Prisma.Applications$jobsArgs<ExtArgs>
  users?: boolean | Prisma.Applications$usersArgs<ExtArgs>
}, ExtArgs["result"]["applications"]>

export type ApplicationsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  status?: boolean
  jobs?: boolean | Prisma.Applications$jobsArgs<ExtArgs>
  users?: boolean | Prisma.Applications$usersArgs<ExtArgs>
}, ExtArgs["result"]["applications"]>

export type ApplicationsSelectScalar = {
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  status?: boolean
}

export type ApplicationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "job_id" | "status", ExtArgs["result"]["applications"]>
export type ApplicationsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.Applications$jobsArgs<ExtArgs>
  users?: boolean | Prisma.Applications$usersArgs<ExtArgs>
}
export type ApplicationsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.Applications$jobsArgs<ExtArgs>
  users?: boolean | Prisma.Applications$usersArgs<ExtArgs>
}
export type ApplicationsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.Applications$jobsArgs<ExtArgs>
  users?: boolean | Prisma.Applications$usersArgs<ExtArgs>
}

export type $ApplicationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Applications"
  objects: {
    jobs: Prisma.$JobsPayload<ExtArgs> | null
    users: Prisma.$UsersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: string | null
    job_id: number | null
    status: $Enums.ApplicationStatus | null
  }, ExtArgs["result"]["applications"]>
  composites: {}
}

export type ApplicationsGetPayload<S extends boolean | null | undefined | ApplicationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload, S>

export type ApplicationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApplicationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApplicationsCountAggregateInputType | true
  }

export interface ApplicationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Applications'], meta: { name: 'Applications' } }
  /**
   * Find zero or one Applications that matches the filter.
   * @param {ApplicationsFindUniqueArgs} args - Arguments to find a Applications
   * @example
   * // Get one Applications
   * const applications = await prisma.applications.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApplicationsFindUniqueArgs>(args: Prisma.SelectSubset<T, ApplicationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Applications that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApplicationsFindUniqueOrThrowArgs} args - Arguments to find a Applications
   * @example
   * // Get one Applications
   * const applications = await prisma.applications.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApplicationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApplicationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Applications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationsFindFirstArgs} args - Arguments to find a Applications
   * @example
   * // Get one Applications
   * const applications = await prisma.applications.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApplicationsFindFirstArgs>(args?: Prisma.SelectSubset<T, ApplicationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Applications that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationsFindFirstOrThrowArgs} args - Arguments to find a Applications
   * @example
   * // Get one Applications
   * const applications = await prisma.applications.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApplicationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApplicationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Applications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Applications
   * const applications = await prisma.applications.findMany()
   * 
   * // Get first 10 Applications
   * const applications = await prisma.applications.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const applicationsWithIdOnly = await prisma.applications.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApplicationsFindManyArgs>(args?: Prisma.SelectSubset<T, ApplicationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Applications.
   * @param {ApplicationsCreateArgs} args - Arguments to create a Applications.
   * @example
   * // Create one Applications
   * const Applications = await prisma.applications.create({
   *   data: {
   *     // ... data to create a Applications
   *   }
   * })
   * 
   */
  create<T extends ApplicationsCreateArgs>(args: Prisma.SelectSubset<T, ApplicationsCreateArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Applications.
   * @param {ApplicationsCreateManyArgs} args - Arguments to create many Applications.
   * @example
   * // Create many Applications
   * const applications = await prisma.applications.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApplicationsCreateManyArgs>(args?: Prisma.SelectSubset<T, ApplicationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Applications and returns the data saved in the database.
   * @param {ApplicationsCreateManyAndReturnArgs} args - Arguments to create many Applications.
   * @example
   * // Create many Applications
   * const applications = await prisma.applications.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Applications and only return the `id`
   * const applicationsWithIdOnly = await prisma.applications.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApplicationsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApplicationsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Applications.
   * @param {ApplicationsDeleteArgs} args - Arguments to delete one Applications.
   * @example
   * // Delete one Applications
   * const Applications = await prisma.applications.delete({
   *   where: {
   *     // ... filter to delete one Applications
   *   }
   * })
   * 
   */
  delete<T extends ApplicationsDeleteArgs>(args: Prisma.SelectSubset<T, ApplicationsDeleteArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Applications.
   * @param {ApplicationsUpdateArgs} args - Arguments to update one Applications.
   * @example
   * // Update one Applications
   * const applications = await prisma.applications.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApplicationsUpdateArgs>(args: Prisma.SelectSubset<T, ApplicationsUpdateArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Applications.
   * @param {ApplicationsDeleteManyArgs} args - Arguments to filter Applications to delete.
   * @example
   * // Delete a few Applications
   * const { count } = await prisma.applications.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApplicationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApplicationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Applications
   * const applications = await prisma.applications.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApplicationsUpdateManyArgs>(args: Prisma.SelectSubset<T, ApplicationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Applications and returns the data updated in the database.
   * @param {ApplicationsUpdateManyAndReturnArgs} args - Arguments to update many Applications.
   * @example
   * // Update many Applications
   * const applications = await prisma.applications.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Applications and only return the `id`
   * const applicationsWithIdOnly = await prisma.applications.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApplicationsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApplicationsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Applications.
   * @param {ApplicationsUpsertArgs} args - Arguments to update or create a Applications.
   * @example
   * // Update or create a Applications
   * const applications = await prisma.applications.upsert({
   *   create: {
   *     // ... data to create a Applications
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Applications we want to update
   *   }
   * })
   */
  upsert<T extends ApplicationsUpsertArgs>(args: Prisma.SelectSubset<T, ApplicationsUpsertArgs<ExtArgs>>): Prisma.Prisma__ApplicationsClient<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationsCountArgs} args - Arguments to filter Applications to count.
   * @example
   * // Count the number of Applications
   * const count = await prisma.applications.count({
   *   where: {
   *     // ... the filter for the Applications we want to count
   *   }
   * })
  **/
  count<T extends ApplicationsCountArgs>(
    args?: Prisma.Subset<T, ApplicationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApplicationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApplicationsAggregateArgs>(args: Prisma.Subset<T, ApplicationsAggregateArgs>): Prisma.PrismaPromise<GetApplicationsAggregateType<T>>

  /**
   * Group by Applications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApplicationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApplicationsGroupByArgs['orderBy'] }
      : { orderBy?: ApplicationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApplicationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApplicationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Applications model
 */
readonly fields: ApplicationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Applications.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApplicationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  jobs<T extends Prisma.Applications$jobsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Applications$jobsArgs<ExtArgs>>): Prisma.Prisma__JobsClient<runtime.Types.Result.GetResult<Prisma.$JobsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.Applications$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Applications$usersArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Applications model
 */
export interface ApplicationsFieldRefs {
  readonly id: Prisma.FieldRef<"Applications", 'Int'>
  readonly user_id: Prisma.FieldRef<"Applications", 'String'>
  readonly job_id: Prisma.FieldRef<"Applications", 'Int'>
  readonly status: Prisma.FieldRef<"Applications", 'ApplicationStatus'>
}
    

// Custom InputTypes
/**
 * Applications findUnique
 */
export type ApplicationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * Filter, which Applications to fetch.
   */
  where: Prisma.ApplicationsWhereUniqueInput
}

/**
 * Applications findUniqueOrThrow
 */
export type ApplicationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * Filter, which Applications to fetch.
   */
  where: Prisma.ApplicationsWhereUniqueInput
}

/**
 * Applications findFirst
 */
export type ApplicationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * Filter, which Applications to fetch.
   */
  where?: Prisma.ApplicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationsOrderByWithRelationInput | Prisma.ApplicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Applications.
   */
  cursor?: Prisma.ApplicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Applications.
   */
  distinct?: Prisma.ApplicationsScalarFieldEnum | Prisma.ApplicationsScalarFieldEnum[]
}

/**
 * Applications findFirstOrThrow
 */
export type ApplicationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * Filter, which Applications to fetch.
   */
  where?: Prisma.ApplicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationsOrderByWithRelationInput | Prisma.ApplicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Applications.
   */
  cursor?: Prisma.ApplicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Applications.
   */
  distinct?: Prisma.ApplicationsScalarFieldEnum | Prisma.ApplicationsScalarFieldEnum[]
}

/**
 * Applications findMany
 */
export type ApplicationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * Filter, which Applications to fetch.
   */
  where?: Prisma.ApplicationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Applications to fetch.
   */
  orderBy?: Prisma.ApplicationsOrderByWithRelationInput | Prisma.ApplicationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Applications.
   */
  cursor?: Prisma.ApplicationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Applications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Applications.
   */
  skip?: number
  distinct?: Prisma.ApplicationsScalarFieldEnum | Prisma.ApplicationsScalarFieldEnum[]
}

/**
 * Applications create
 */
export type ApplicationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * The data needed to create a Applications.
   */
  data?: Prisma.XOR<Prisma.ApplicationsCreateInput, Prisma.ApplicationsUncheckedCreateInput>
}

/**
 * Applications createMany
 */
export type ApplicationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Applications.
   */
  data: Prisma.ApplicationsCreateManyInput | Prisma.ApplicationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Applications createManyAndReturn
 */
export type ApplicationsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * The data used to create many Applications.
   */
  data: Prisma.ApplicationsCreateManyInput | Prisma.ApplicationsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Applications update
 */
export type ApplicationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * The data needed to update a Applications.
   */
  data: Prisma.XOR<Prisma.ApplicationsUpdateInput, Prisma.ApplicationsUncheckedUpdateInput>
  /**
   * Choose, which Applications to update.
   */
  where: Prisma.ApplicationsWhereUniqueInput
}

/**
 * Applications updateMany
 */
export type ApplicationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Applications.
   */
  data: Prisma.XOR<Prisma.ApplicationsUpdateManyMutationInput, Prisma.ApplicationsUncheckedUpdateManyInput>
  /**
   * Filter which Applications to update
   */
  where?: Prisma.ApplicationsWhereInput
  /**
   * Limit how many Applications to update.
   */
  limit?: number
}

/**
 * Applications updateManyAndReturn
 */
export type ApplicationsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * The data used to update Applications.
   */
  data: Prisma.XOR<Prisma.ApplicationsUpdateManyMutationInput, Prisma.ApplicationsUncheckedUpdateManyInput>
  /**
   * Filter which Applications to update
   */
  where?: Prisma.ApplicationsWhereInput
  /**
   * Limit how many Applications to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Applications upsert
 */
export type ApplicationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * The filter to search for the Applications to update in case it exists.
   */
  where: Prisma.ApplicationsWhereUniqueInput
  /**
   * In case the Applications found by the `where` argument doesn't exist, create a new Applications with this data.
   */
  create: Prisma.XOR<Prisma.ApplicationsCreateInput, Prisma.ApplicationsUncheckedCreateInput>
  /**
   * In case the Applications was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApplicationsUpdateInput, Prisma.ApplicationsUncheckedUpdateInput>
}

/**
 * Applications delete
 */
export type ApplicationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  /**
   * Filter which Applications to delete.
   */
  where: Prisma.ApplicationsWhereUniqueInput
}

/**
 * Applications deleteMany
 */
export type ApplicationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Applications to delete
   */
  where?: Prisma.ApplicationsWhereInput
  /**
   * Limit how many Applications to delete.
   */
  limit?: number
}

/**
 * Applications.jobs
 */
export type Applications$jobsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Jobs
   */
  select?: Prisma.JobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Jobs
   */
  omit?: Prisma.JobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobsInclude<ExtArgs> | null
  where?: Prisma.JobsWhereInput
}

/**
 * Applications.users
 */
export type Applications$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  where?: Prisma.UsersWhereInput
}

/**
 * Applications without action
 */
export type ApplicationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
}
