
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JobSkills` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model JobSkills
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type JobSkillsModel = runtime.Types.Result.DefaultSelection<Prisma.$JobSkillsPayload>

export type AggregateJobSkills = {
  _count: JobSkillsCountAggregateOutputType | null
  _avg: JobSkillsAvgAggregateOutputType | null
  _sum: JobSkillsSumAggregateOutputType | null
  _min: JobSkillsMinAggregateOutputType | null
  _max: JobSkillsMaxAggregateOutputType | null
}

export type JobSkillsAvgAggregateOutputType = {
  id: number | null
  job_id: number | null
  skill_id: number | null
  required_level: number | null
}

export type JobSkillsSumAggregateOutputType = {
  id: number | null
  job_id: number | null
  skill_id: number | null
  required_level: number | null
}

export type JobSkillsMinAggregateOutputType = {
  id: number | null
  job_id: number | null
  skill_id: number | null
  required_level: number | null
}

export type JobSkillsMaxAggregateOutputType = {
  id: number | null
  job_id: number | null
  skill_id: number | null
  required_level: number | null
}

export type JobSkillsCountAggregateOutputType = {
  id: number
  job_id: number
  skill_id: number
  required_level: number
  _all: number
}


export type JobSkillsAvgAggregateInputType = {
  id?: true
  job_id?: true
  skill_id?: true
  required_level?: true
}

export type JobSkillsSumAggregateInputType = {
  id?: true
  job_id?: true
  skill_id?: true
  required_level?: true
}

export type JobSkillsMinAggregateInputType = {
  id?: true
  job_id?: true
  skill_id?: true
  required_level?: true
}

export type JobSkillsMaxAggregateInputType = {
  id?: true
  job_id?: true
  skill_id?: true
  required_level?: true
}

export type JobSkillsCountAggregateInputType = {
  id?: true
  job_id?: true
  skill_id?: true
  required_level?: true
  _all?: true
}

export type JobSkillsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JobSkills to aggregate.
   */
  where?: Prisma.JobSkillsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobSkills to fetch.
   */
  orderBy?: Prisma.JobSkillsOrderByWithRelationInput | Prisma.JobSkillsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JobSkillsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JobSkills
  **/
  _count?: true | JobSkillsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: JobSkillsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: JobSkillsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JobSkillsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JobSkillsMaxAggregateInputType
}

export type GetJobSkillsAggregateType<T extends JobSkillsAggregateArgs> = {
      [P in keyof T & keyof AggregateJobSkills]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJobSkills[P]>
    : Prisma.GetScalarType<T[P], AggregateJobSkills[P]>
}




export type JobSkillsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JobSkillsWhereInput
  orderBy?: Prisma.JobSkillsOrderByWithAggregationInput | Prisma.JobSkillsOrderByWithAggregationInput[]
  by: Prisma.JobSkillsScalarFieldEnum[] | Prisma.JobSkillsScalarFieldEnum
  having?: Prisma.JobSkillsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JobSkillsCountAggregateInputType | true
  _avg?: JobSkillsAvgAggregateInputType
  _sum?: JobSkillsSumAggregateInputType
  _min?: JobSkillsMinAggregateInputType
  _max?: JobSkillsMaxAggregateInputType
}

export type JobSkillsGroupByOutputType = {
  id: number
  job_id: number | null
  skill_id: number | null
  required_level: number | null
  _count: JobSkillsCountAggregateOutputType | null
  _avg: JobSkillsAvgAggregateOutputType | null
  _sum: JobSkillsSumAggregateOutputType | null
  _min: JobSkillsMinAggregateOutputType | null
  _max: JobSkillsMaxAggregateOutputType | null
}

type GetJobSkillsGroupByPayload<T extends JobSkillsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JobSkillsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JobSkillsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JobSkillsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JobSkillsGroupByOutputType[P]>
      }
    >
  >



export type JobSkillsWhereInput = {
  AND?: Prisma.JobSkillsWhereInput | Prisma.JobSkillsWhereInput[]
  OR?: Prisma.JobSkillsWhereInput[]
  NOT?: Prisma.JobSkillsWhereInput | Prisma.JobSkillsWhereInput[]
  id?: Prisma.IntFilter<"JobSkills"> | number
  job_id?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  skill_id?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  required_level?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  jobs?: Prisma.XOR<Prisma.JobsNullableScalarRelationFilter, Prisma.JobsWhereInput> | null
  skills?: Prisma.XOR<Prisma.SkillsNullableScalarRelationFilter, Prisma.SkillsWhereInput> | null
}

export type JobSkillsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrderInput | Prisma.SortOrder
  skill_id?: Prisma.SortOrderInput | Prisma.SortOrder
  required_level?: Prisma.SortOrderInput | Prisma.SortOrder
  jobs?: Prisma.JobsOrderByWithRelationInput
  skills?: Prisma.SkillsOrderByWithRelationInput
}

export type JobSkillsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.JobSkillsWhereInput | Prisma.JobSkillsWhereInput[]
  OR?: Prisma.JobSkillsWhereInput[]
  NOT?: Prisma.JobSkillsWhereInput | Prisma.JobSkillsWhereInput[]
  job_id?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  skill_id?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  required_level?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  jobs?: Prisma.XOR<Prisma.JobsNullableScalarRelationFilter, Prisma.JobsWhereInput> | null
  skills?: Prisma.XOR<Prisma.SkillsNullableScalarRelationFilter, Prisma.SkillsWhereInput> | null
}, "id">

export type JobSkillsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrderInput | Prisma.SortOrder
  skill_id?: Prisma.SortOrderInput | Prisma.SortOrder
  required_level?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.JobSkillsCountOrderByAggregateInput
  _avg?: Prisma.JobSkillsAvgOrderByAggregateInput
  _max?: Prisma.JobSkillsMaxOrderByAggregateInput
  _min?: Prisma.JobSkillsMinOrderByAggregateInput
  _sum?: Prisma.JobSkillsSumOrderByAggregateInput
}

export type JobSkillsScalarWhereWithAggregatesInput = {
  AND?: Prisma.JobSkillsScalarWhereWithAggregatesInput | Prisma.JobSkillsScalarWhereWithAggregatesInput[]
  OR?: Prisma.JobSkillsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JobSkillsScalarWhereWithAggregatesInput | Prisma.JobSkillsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"JobSkills"> | number
  job_id?: Prisma.IntNullableWithAggregatesFilter<"JobSkills"> | number | null
  skill_id?: Prisma.IntNullableWithAggregatesFilter<"JobSkills"> | number | null
  required_level?: Prisma.IntNullableWithAggregatesFilter<"JobSkills"> | number | null
}

export type JobSkillsCreateInput = {
  required_level?: number | null
  jobs?: Prisma.JobsCreateNestedOneWithoutJob_skillsInput
  skills?: Prisma.SkillsCreateNestedOneWithoutJob_skillsInput
}

export type JobSkillsUncheckedCreateInput = {
  id?: number
  job_id?: number | null
  skill_id?: number | null
  required_level?: number | null
}

export type JobSkillsUpdateInput = {
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  jobs?: Prisma.JobsUpdateOneWithoutJob_skillsNestedInput
  skills?: Prisma.SkillsUpdateOneWithoutJob_skillsNestedInput
}

export type JobSkillsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  skill_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type JobSkillsCreateManyInput = {
  id?: number
  job_id?: number | null
  skill_id?: number | null
  required_level?: number | null
}

export type JobSkillsUpdateManyMutationInput = {
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type JobSkillsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  skill_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type JobSkillsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  required_level?: Prisma.SortOrder
}

export type JobSkillsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  required_level?: Prisma.SortOrder
}

export type JobSkillsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  required_level?: Prisma.SortOrder
}

export type JobSkillsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  required_level?: Prisma.SortOrder
}

export type JobSkillsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  skill_id?: Prisma.SortOrder
  required_level?: Prisma.SortOrder
}

export type JobSkillsListRelationFilter = {
  every?: Prisma.JobSkillsWhereInput
  some?: Prisma.JobSkillsWhereInput
  none?: Prisma.JobSkillsWhereInput
}

export type JobSkillsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type JobSkillsCreateNestedManyWithoutJobsInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutJobsInput, Prisma.JobSkillsUncheckedCreateWithoutJobsInput> | Prisma.JobSkillsCreateWithoutJobsInput[] | Prisma.JobSkillsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutJobsInput | Prisma.JobSkillsCreateOrConnectWithoutJobsInput[]
  createMany?: Prisma.JobSkillsCreateManyJobsInputEnvelope
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
}

export type JobSkillsUncheckedCreateNestedManyWithoutJobsInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutJobsInput, Prisma.JobSkillsUncheckedCreateWithoutJobsInput> | Prisma.JobSkillsCreateWithoutJobsInput[] | Prisma.JobSkillsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutJobsInput | Prisma.JobSkillsCreateOrConnectWithoutJobsInput[]
  createMany?: Prisma.JobSkillsCreateManyJobsInputEnvelope
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
}

export type JobSkillsUpdateManyWithoutJobsNestedInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutJobsInput, Prisma.JobSkillsUncheckedCreateWithoutJobsInput> | Prisma.JobSkillsCreateWithoutJobsInput[] | Prisma.JobSkillsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutJobsInput | Prisma.JobSkillsCreateOrConnectWithoutJobsInput[]
  upsert?: Prisma.JobSkillsUpsertWithWhereUniqueWithoutJobsInput | Prisma.JobSkillsUpsertWithWhereUniqueWithoutJobsInput[]
  createMany?: Prisma.JobSkillsCreateManyJobsInputEnvelope
  set?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  disconnect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  delete?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  update?: Prisma.JobSkillsUpdateWithWhereUniqueWithoutJobsInput | Prisma.JobSkillsUpdateWithWhereUniqueWithoutJobsInput[]
  updateMany?: Prisma.JobSkillsUpdateManyWithWhereWithoutJobsInput | Prisma.JobSkillsUpdateManyWithWhereWithoutJobsInput[]
  deleteMany?: Prisma.JobSkillsScalarWhereInput | Prisma.JobSkillsScalarWhereInput[]
}

export type JobSkillsUncheckedUpdateManyWithoutJobsNestedInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutJobsInput, Prisma.JobSkillsUncheckedCreateWithoutJobsInput> | Prisma.JobSkillsCreateWithoutJobsInput[] | Prisma.JobSkillsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutJobsInput | Prisma.JobSkillsCreateOrConnectWithoutJobsInput[]
  upsert?: Prisma.JobSkillsUpsertWithWhereUniqueWithoutJobsInput | Prisma.JobSkillsUpsertWithWhereUniqueWithoutJobsInput[]
  createMany?: Prisma.JobSkillsCreateManyJobsInputEnvelope
  set?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  disconnect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  delete?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  update?: Prisma.JobSkillsUpdateWithWhereUniqueWithoutJobsInput | Prisma.JobSkillsUpdateWithWhereUniqueWithoutJobsInput[]
  updateMany?: Prisma.JobSkillsUpdateManyWithWhereWithoutJobsInput | Prisma.JobSkillsUpdateManyWithWhereWithoutJobsInput[]
  deleteMany?: Prisma.JobSkillsScalarWhereInput | Prisma.JobSkillsScalarWhereInput[]
}

export type JobSkillsCreateNestedManyWithoutSkillsInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutSkillsInput, Prisma.JobSkillsUncheckedCreateWithoutSkillsInput> | Prisma.JobSkillsCreateWithoutSkillsInput[] | Prisma.JobSkillsUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutSkillsInput | Prisma.JobSkillsCreateOrConnectWithoutSkillsInput[]
  createMany?: Prisma.JobSkillsCreateManySkillsInputEnvelope
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
}

export type JobSkillsUncheckedCreateNestedManyWithoutSkillsInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutSkillsInput, Prisma.JobSkillsUncheckedCreateWithoutSkillsInput> | Prisma.JobSkillsCreateWithoutSkillsInput[] | Prisma.JobSkillsUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutSkillsInput | Prisma.JobSkillsCreateOrConnectWithoutSkillsInput[]
  createMany?: Prisma.JobSkillsCreateManySkillsInputEnvelope
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
}

export type JobSkillsUpdateManyWithoutSkillsNestedInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutSkillsInput, Prisma.JobSkillsUncheckedCreateWithoutSkillsInput> | Prisma.JobSkillsCreateWithoutSkillsInput[] | Prisma.JobSkillsUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutSkillsInput | Prisma.JobSkillsCreateOrConnectWithoutSkillsInput[]
  upsert?: Prisma.JobSkillsUpsertWithWhereUniqueWithoutSkillsInput | Prisma.JobSkillsUpsertWithWhereUniqueWithoutSkillsInput[]
  createMany?: Prisma.JobSkillsCreateManySkillsInputEnvelope
  set?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  disconnect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  delete?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  update?: Prisma.JobSkillsUpdateWithWhereUniqueWithoutSkillsInput | Prisma.JobSkillsUpdateWithWhereUniqueWithoutSkillsInput[]
  updateMany?: Prisma.JobSkillsUpdateManyWithWhereWithoutSkillsInput | Prisma.JobSkillsUpdateManyWithWhereWithoutSkillsInput[]
  deleteMany?: Prisma.JobSkillsScalarWhereInput | Prisma.JobSkillsScalarWhereInput[]
}

export type JobSkillsUncheckedUpdateManyWithoutSkillsNestedInput = {
  create?: Prisma.XOR<Prisma.JobSkillsCreateWithoutSkillsInput, Prisma.JobSkillsUncheckedCreateWithoutSkillsInput> | Prisma.JobSkillsCreateWithoutSkillsInput[] | Prisma.JobSkillsUncheckedCreateWithoutSkillsInput[]
  connectOrCreate?: Prisma.JobSkillsCreateOrConnectWithoutSkillsInput | Prisma.JobSkillsCreateOrConnectWithoutSkillsInput[]
  upsert?: Prisma.JobSkillsUpsertWithWhereUniqueWithoutSkillsInput | Prisma.JobSkillsUpsertWithWhereUniqueWithoutSkillsInput[]
  createMany?: Prisma.JobSkillsCreateManySkillsInputEnvelope
  set?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  disconnect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  delete?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  connect?: Prisma.JobSkillsWhereUniqueInput | Prisma.JobSkillsWhereUniqueInput[]
  update?: Prisma.JobSkillsUpdateWithWhereUniqueWithoutSkillsInput | Prisma.JobSkillsUpdateWithWhereUniqueWithoutSkillsInput[]
  updateMany?: Prisma.JobSkillsUpdateManyWithWhereWithoutSkillsInput | Prisma.JobSkillsUpdateManyWithWhereWithoutSkillsInput[]
  deleteMany?: Prisma.JobSkillsScalarWhereInput | Prisma.JobSkillsScalarWhereInput[]
}

export type JobSkillsCreateWithoutJobsInput = {
  required_level?: number | null
  skills?: Prisma.SkillsCreateNestedOneWithoutJob_skillsInput
}

export type JobSkillsUncheckedCreateWithoutJobsInput = {
  id?: number
  skill_id?: number | null
  required_level?: number | null
}

export type JobSkillsCreateOrConnectWithoutJobsInput = {
  where: Prisma.JobSkillsWhereUniqueInput
  create: Prisma.XOR<Prisma.JobSkillsCreateWithoutJobsInput, Prisma.JobSkillsUncheckedCreateWithoutJobsInput>
}

export type JobSkillsCreateManyJobsInputEnvelope = {
  data: Prisma.JobSkillsCreateManyJobsInput | Prisma.JobSkillsCreateManyJobsInput[]
  skipDuplicates?: boolean
}

export type JobSkillsUpsertWithWhereUniqueWithoutJobsInput = {
  where: Prisma.JobSkillsWhereUniqueInput
  update: Prisma.XOR<Prisma.JobSkillsUpdateWithoutJobsInput, Prisma.JobSkillsUncheckedUpdateWithoutJobsInput>
  create: Prisma.XOR<Prisma.JobSkillsCreateWithoutJobsInput, Prisma.JobSkillsUncheckedCreateWithoutJobsInput>
}

export type JobSkillsUpdateWithWhereUniqueWithoutJobsInput = {
  where: Prisma.JobSkillsWhereUniqueInput
  data: Prisma.XOR<Prisma.JobSkillsUpdateWithoutJobsInput, Prisma.JobSkillsUncheckedUpdateWithoutJobsInput>
}

export type JobSkillsUpdateManyWithWhereWithoutJobsInput = {
  where: Prisma.JobSkillsScalarWhereInput
  data: Prisma.XOR<Prisma.JobSkillsUpdateManyMutationInput, Prisma.JobSkillsUncheckedUpdateManyWithoutJobsInput>
}

export type JobSkillsScalarWhereInput = {
  AND?: Prisma.JobSkillsScalarWhereInput | Prisma.JobSkillsScalarWhereInput[]
  OR?: Prisma.JobSkillsScalarWhereInput[]
  NOT?: Prisma.JobSkillsScalarWhereInput | Prisma.JobSkillsScalarWhereInput[]
  id?: Prisma.IntFilter<"JobSkills"> | number
  job_id?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  skill_id?: Prisma.IntNullableFilter<"JobSkills"> | number | null
  required_level?: Prisma.IntNullableFilter<"JobSkills"> | number | null
}

export type JobSkillsCreateWithoutSkillsInput = {
  required_level?: number | null
  jobs?: Prisma.JobsCreateNestedOneWithoutJob_skillsInput
}

export type JobSkillsUncheckedCreateWithoutSkillsInput = {
  id?: number
  job_id?: number | null
  required_level?: number | null
}

export type JobSkillsCreateOrConnectWithoutSkillsInput = {
  where: Prisma.JobSkillsWhereUniqueInput
  create: Prisma.XOR<Prisma.JobSkillsCreateWithoutSkillsInput, Prisma.JobSkillsUncheckedCreateWithoutSkillsInput>
}

export type JobSkillsCreateManySkillsInputEnvelope = {
  data: Prisma.JobSkillsCreateManySkillsInput | Prisma.JobSkillsCreateManySkillsInput[]
  skipDuplicates?: boolean
}

export type JobSkillsUpsertWithWhereUniqueWithoutSkillsInput = {
  where: Prisma.JobSkillsWhereUniqueInput
  update: Prisma.XOR<Prisma.JobSkillsUpdateWithoutSkillsInput, Prisma.JobSkillsUncheckedUpdateWithoutSkillsInput>
  create: Prisma.XOR<Prisma.JobSkillsCreateWithoutSkillsInput, Prisma.JobSkillsUncheckedCreateWithoutSkillsInput>
}

export type JobSkillsUpdateWithWhereUniqueWithoutSkillsInput = {
  where: Prisma.JobSkillsWhereUniqueInput
  data: Prisma.XOR<Prisma.JobSkillsUpdateWithoutSkillsInput, Prisma.JobSkillsUncheckedUpdateWithoutSkillsInput>
}

export type JobSkillsUpdateManyWithWhereWithoutSkillsInput = {
  where: Prisma.JobSkillsScalarWhereInput
  data: Prisma.XOR<Prisma.JobSkillsUpdateManyMutationInput, Prisma.JobSkillsUncheckedUpdateManyWithoutSkillsInput>
}

export type JobSkillsCreateManyJobsInput = {
  id?: number
  skill_id?: number | null
  required_level?: number | null
}

export type JobSkillsUpdateWithoutJobsInput = {
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  skills?: Prisma.SkillsUpdateOneWithoutJob_skillsNestedInput
}

export type JobSkillsUncheckedUpdateWithoutJobsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  skill_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type JobSkillsUncheckedUpdateManyWithoutJobsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  skill_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type JobSkillsCreateManySkillsInput = {
  id?: number
  job_id?: number | null
  required_level?: number | null
}

export type JobSkillsUpdateWithoutSkillsInput = {
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  jobs?: Prisma.JobsUpdateOneWithoutJob_skillsNestedInput
}

export type JobSkillsUncheckedUpdateWithoutSkillsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type JobSkillsUncheckedUpdateManyWithoutSkillsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  required_level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type JobSkillsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  job_id?: boolean
  skill_id?: boolean
  required_level?: boolean
  jobs?: boolean | Prisma.JobSkills$jobsArgs<ExtArgs>
  skills?: boolean | Prisma.JobSkills$skillsArgs<ExtArgs>
}, ExtArgs["result"]["jobSkills"]>

export type JobSkillsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  job_id?: boolean
  skill_id?: boolean
  required_level?: boolean
  jobs?: boolean | Prisma.JobSkills$jobsArgs<ExtArgs>
  skills?: boolean | Prisma.JobSkills$skillsArgs<ExtArgs>
}, ExtArgs["result"]["jobSkills"]>

export type JobSkillsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  job_id?: boolean
  skill_id?: boolean
  required_level?: boolean
  jobs?: boolean | Prisma.JobSkills$jobsArgs<ExtArgs>
  skills?: boolean | Prisma.JobSkills$skillsArgs<ExtArgs>
}, ExtArgs["result"]["jobSkills"]>

export type JobSkillsSelectScalar = {
  id?: boolean
  job_id?: boolean
  skill_id?: boolean
  required_level?: boolean
}

export type JobSkillsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "job_id" | "skill_id" | "required_level", ExtArgs["result"]["jobSkills"]>
export type JobSkillsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.JobSkills$jobsArgs<ExtArgs>
  skills?: boolean | Prisma.JobSkills$skillsArgs<ExtArgs>
}
export type JobSkillsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.JobSkills$jobsArgs<ExtArgs>
  skills?: boolean | Prisma.JobSkills$skillsArgs<ExtArgs>
}
export type JobSkillsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.JobSkills$jobsArgs<ExtArgs>
  skills?: boolean | Prisma.JobSkills$skillsArgs<ExtArgs>
}

export type $JobSkillsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JobSkills"
  objects: {
    jobs: Prisma.$JobsPayload<ExtArgs> | null
    skills: Prisma.$SkillsPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    job_id: number | null
    skill_id: number | null
    required_level: number | null
  }, ExtArgs["result"]["jobSkills"]>
  composites: {}
}

export type JobSkillsGetPayload<S extends boolean | null | undefined | JobSkillsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload, S>

export type JobSkillsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JobSkillsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JobSkillsCountAggregateInputType | true
  }

export interface JobSkillsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JobSkills'], meta: { name: 'JobSkills' } }
  /**
   * Find zero or one JobSkills that matches the filter.
   * @param {JobSkillsFindUniqueArgs} args - Arguments to find a JobSkills
   * @example
   * // Get one JobSkills
   * const jobSkills = await prisma.jobSkills.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JobSkillsFindUniqueArgs>(args: Prisma.SelectSubset<T, JobSkillsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JobSkills that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JobSkillsFindUniqueOrThrowArgs} args - Arguments to find a JobSkills
   * @example
   * // Get one JobSkills
   * const jobSkills = await prisma.jobSkills.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JobSkillsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JobSkillsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JobSkills that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobSkillsFindFirstArgs} args - Arguments to find a JobSkills
   * @example
   * // Get one JobSkills
   * const jobSkills = await prisma.jobSkills.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JobSkillsFindFirstArgs>(args?: Prisma.SelectSubset<T, JobSkillsFindFirstArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JobSkills that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobSkillsFindFirstOrThrowArgs} args - Arguments to find a JobSkills
   * @example
   * // Get one JobSkills
   * const jobSkills = await prisma.jobSkills.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JobSkillsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JobSkillsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JobSkills that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobSkillsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JobSkills
   * const jobSkills = await prisma.jobSkills.findMany()
   * 
   * // Get first 10 JobSkills
   * const jobSkills = await prisma.jobSkills.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const jobSkillsWithIdOnly = await prisma.jobSkills.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JobSkillsFindManyArgs>(args?: Prisma.SelectSubset<T, JobSkillsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JobSkills.
   * @param {JobSkillsCreateArgs} args - Arguments to create a JobSkills.
   * @example
   * // Create one JobSkills
   * const JobSkills = await prisma.jobSkills.create({
   *   data: {
   *     // ... data to create a JobSkills
   *   }
   * })
   * 
   */
  create<T extends JobSkillsCreateArgs>(args: Prisma.SelectSubset<T, JobSkillsCreateArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JobSkills.
   * @param {JobSkillsCreateManyArgs} args - Arguments to create many JobSkills.
   * @example
   * // Create many JobSkills
   * const jobSkills = await prisma.jobSkills.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JobSkillsCreateManyArgs>(args?: Prisma.SelectSubset<T, JobSkillsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JobSkills and returns the data saved in the database.
   * @param {JobSkillsCreateManyAndReturnArgs} args - Arguments to create many JobSkills.
   * @example
   * // Create many JobSkills
   * const jobSkills = await prisma.jobSkills.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JobSkills and only return the `id`
   * const jobSkillsWithIdOnly = await prisma.jobSkills.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JobSkillsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JobSkillsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JobSkills.
   * @param {JobSkillsDeleteArgs} args - Arguments to delete one JobSkills.
   * @example
   * // Delete one JobSkills
   * const JobSkills = await prisma.jobSkills.delete({
   *   where: {
   *     // ... filter to delete one JobSkills
   *   }
   * })
   * 
   */
  delete<T extends JobSkillsDeleteArgs>(args: Prisma.SelectSubset<T, JobSkillsDeleteArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JobSkills.
   * @param {JobSkillsUpdateArgs} args - Arguments to update one JobSkills.
   * @example
   * // Update one JobSkills
   * const jobSkills = await prisma.jobSkills.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JobSkillsUpdateArgs>(args: Prisma.SelectSubset<T, JobSkillsUpdateArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JobSkills.
   * @param {JobSkillsDeleteManyArgs} args - Arguments to filter JobSkills to delete.
   * @example
   * // Delete a few JobSkills
   * const { count } = await prisma.jobSkills.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JobSkillsDeleteManyArgs>(args?: Prisma.SelectSubset<T, JobSkillsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JobSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobSkillsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JobSkills
   * const jobSkills = await prisma.jobSkills.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JobSkillsUpdateManyArgs>(args: Prisma.SelectSubset<T, JobSkillsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JobSkills and returns the data updated in the database.
   * @param {JobSkillsUpdateManyAndReturnArgs} args - Arguments to update many JobSkills.
   * @example
   * // Update many JobSkills
   * const jobSkills = await prisma.jobSkills.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JobSkills and only return the `id`
   * const jobSkillsWithIdOnly = await prisma.jobSkills.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JobSkillsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JobSkillsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JobSkills.
   * @param {JobSkillsUpsertArgs} args - Arguments to update or create a JobSkills.
   * @example
   * // Update or create a JobSkills
   * const jobSkills = await prisma.jobSkills.upsert({
   *   create: {
   *     // ... data to create a JobSkills
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JobSkills we want to update
   *   }
   * })
   */
  upsert<T extends JobSkillsUpsertArgs>(args: Prisma.SelectSubset<T, JobSkillsUpsertArgs<ExtArgs>>): Prisma.Prisma__JobSkillsClient<runtime.Types.Result.GetResult<Prisma.$JobSkillsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JobSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobSkillsCountArgs} args - Arguments to filter JobSkills to count.
   * @example
   * // Count the number of JobSkills
   * const count = await prisma.jobSkills.count({
   *   where: {
   *     // ... the filter for the JobSkills we want to count
   *   }
   * })
  **/
  count<T extends JobSkillsCountArgs>(
    args?: Prisma.Subset<T, JobSkillsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JobSkillsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JobSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobSkillsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JobSkillsAggregateArgs>(args: Prisma.Subset<T, JobSkillsAggregateArgs>): Prisma.PrismaPromise<GetJobSkillsAggregateType<T>>

  /**
   * Group by JobSkills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobSkillsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JobSkillsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JobSkillsGroupByArgs['orderBy'] }
      : { orderBy?: JobSkillsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JobSkillsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJobSkillsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JobSkills model
 */
readonly fields: JobSkillsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JobSkills.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JobSkillsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  jobs<T extends Prisma.JobSkills$jobsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JobSkills$jobsArgs<ExtArgs>>): Prisma.Prisma__JobsClient<runtime.Types.Result.GetResult<Prisma.$JobsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  skills<T extends Prisma.JobSkills$skillsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JobSkills$skillsArgs<ExtArgs>>): Prisma.Prisma__SkillsClient<runtime.Types.Result.GetResult<Prisma.$SkillsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JobSkills model
 */
export interface JobSkillsFieldRefs {
  readonly id: Prisma.FieldRef<"JobSkills", 'Int'>
  readonly job_id: Prisma.FieldRef<"JobSkills", 'Int'>
  readonly skill_id: Prisma.FieldRef<"JobSkills", 'Int'>
  readonly required_level: Prisma.FieldRef<"JobSkills", 'Int'>
}
    

// Custom InputTypes
/**
 * JobSkills findUnique
 */
export type JobSkillsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * Filter, which JobSkills to fetch.
   */
  where: Prisma.JobSkillsWhereUniqueInput
}

/**
 * JobSkills findUniqueOrThrow
 */
export type JobSkillsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * Filter, which JobSkills to fetch.
   */
  where: Prisma.JobSkillsWhereUniqueInput
}

/**
 * JobSkills findFirst
 */
export type JobSkillsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * Filter, which JobSkills to fetch.
   */
  where?: Prisma.JobSkillsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobSkills to fetch.
   */
  orderBy?: Prisma.JobSkillsOrderByWithRelationInput | Prisma.JobSkillsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JobSkills.
   */
  cursor?: Prisma.JobSkillsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JobSkills.
   */
  distinct?: Prisma.JobSkillsScalarFieldEnum | Prisma.JobSkillsScalarFieldEnum[]
}

/**
 * JobSkills findFirstOrThrow
 */
export type JobSkillsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * Filter, which JobSkills to fetch.
   */
  where?: Prisma.JobSkillsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobSkills to fetch.
   */
  orderBy?: Prisma.JobSkillsOrderByWithRelationInput | Prisma.JobSkillsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JobSkills.
   */
  cursor?: Prisma.JobSkillsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobSkills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JobSkills.
   */
  distinct?: Prisma.JobSkillsScalarFieldEnum | Prisma.JobSkillsScalarFieldEnum[]
}

/**
 * JobSkills findMany
 */
export type JobSkillsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * Filter, which JobSkills to fetch.
   */
  where?: Prisma.JobSkillsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobSkills to fetch.
   */
  orderBy?: Prisma.JobSkillsOrderByWithRelationInput | Prisma.JobSkillsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JobSkills.
   */
  cursor?: Prisma.JobSkillsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobSkills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobSkills.
   */
  skip?: number
  distinct?: Prisma.JobSkillsScalarFieldEnum | Prisma.JobSkillsScalarFieldEnum[]
}

/**
 * JobSkills create
 */
export type JobSkillsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * The data needed to create a JobSkills.
   */
  data?: Prisma.XOR<Prisma.JobSkillsCreateInput, Prisma.JobSkillsUncheckedCreateInput>
}

/**
 * JobSkills createMany
 */
export type JobSkillsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JobSkills.
   */
  data: Prisma.JobSkillsCreateManyInput | Prisma.JobSkillsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JobSkills createManyAndReturn
 */
export type JobSkillsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * The data used to create many JobSkills.
   */
  data: Prisma.JobSkillsCreateManyInput | Prisma.JobSkillsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * JobSkills update
 */
export type JobSkillsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * The data needed to update a JobSkills.
   */
  data: Prisma.XOR<Prisma.JobSkillsUpdateInput, Prisma.JobSkillsUncheckedUpdateInput>
  /**
   * Choose, which JobSkills to update.
   */
  where: Prisma.JobSkillsWhereUniqueInput
}

/**
 * JobSkills updateMany
 */
export type JobSkillsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JobSkills.
   */
  data: Prisma.XOR<Prisma.JobSkillsUpdateManyMutationInput, Prisma.JobSkillsUncheckedUpdateManyInput>
  /**
   * Filter which JobSkills to update
   */
  where?: Prisma.JobSkillsWhereInput
  /**
   * Limit how many JobSkills to update.
   */
  limit?: number
}

/**
 * JobSkills updateManyAndReturn
 */
export type JobSkillsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * The data used to update JobSkills.
   */
  data: Prisma.XOR<Prisma.JobSkillsUpdateManyMutationInput, Prisma.JobSkillsUncheckedUpdateManyInput>
  /**
   * Filter which JobSkills to update
   */
  where?: Prisma.JobSkillsWhereInput
  /**
   * Limit how many JobSkills to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * JobSkills upsert
 */
export type JobSkillsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * The filter to search for the JobSkills to update in case it exists.
   */
  where: Prisma.JobSkillsWhereUniqueInput
  /**
   * In case the JobSkills found by the `where` argument doesn't exist, create a new JobSkills with this data.
   */
  create: Prisma.XOR<Prisma.JobSkillsCreateInput, Prisma.JobSkillsUncheckedCreateInput>
  /**
   * In case the JobSkills was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JobSkillsUpdateInput, Prisma.JobSkillsUncheckedUpdateInput>
}

/**
 * JobSkills delete
 */
export type JobSkillsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
  /**
   * Filter which JobSkills to delete.
   */
  where: Prisma.JobSkillsWhereUniqueInput
}

/**
 * JobSkills deleteMany
 */
export type JobSkillsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JobSkills to delete
   */
  where?: Prisma.JobSkillsWhereInput
  /**
   * Limit how many JobSkills to delete.
   */
  limit?: number
}

/**
 * JobSkills.jobs
 */
export type JobSkills$jobsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Jobs
   */
  select?: Prisma.JobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Jobs
   */
  omit?: Prisma.JobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobsInclude<ExtArgs> | null
  where?: Prisma.JobsWhereInput
}

/**
 * JobSkills.skills
 */
export type JobSkills$skillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skills
   */
  select?: Prisma.SkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skills
   */
  omit?: Prisma.SkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillsInclude<ExtArgs> | null
  where?: Prisma.SkillsWhereInput
}

/**
 * JobSkills without action
 */
export type JobSkillsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobSkills
   */
  select?: Prisma.JobSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobSkills
   */
  omit?: Prisma.JobSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobSkillsInclude<ExtArgs> | null
}
