
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MatchResults` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model MatchResults
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type MatchResultsModel = runtime.Types.Result.DefaultSelection<Prisma.$MatchResultsPayload>

export type AggregateMatchResults = {
  _count: MatchResultsCountAggregateOutputType | null
  _avg: MatchResultsAvgAggregateOutputType | null
  _sum: MatchResultsSumAggregateOutputType | null
  _min: MatchResultsMinAggregateOutputType | null
  _max: MatchResultsMaxAggregateOutputType | null
}

export type MatchResultsAvgAggregateOutputType = {
  id: number | null
  job_id: number | null
  match_percentage: runtime.Decimal | null
}

export type MatchResultsSumAggregateOutputType = {
  id: number | null
  job_id: number | null
  match_percentage: runtime.Decimal | null
}

export type MatchResultsMinAggregateOutputType = {
  id: number | null
  user_id: string | null
  job_id: number | null
  match_percentage: runtime.Decimal | null
  recommendation_type: string | null
}

export type MatchResultsMaxAggregateOutputType = {
  id: number | null
  user_id: string | null
  job_id: number | null
  match_percentage: runtime.Decimal | null
  recommendation_type: string | null
}

export type MatchResultsCountAggregateOutputType = {
  id: number
  user_id: number
  job_id: number
  match_percentage: number
  recommendation_type: number
  _all: number
}


export type MatchResultsAvgAggregateInputType = {
  id?: true
  job_id?: true
  match_percentage?: true
}

export type MatchResultsSumAggregateInputType = {
  id?: true
  job_id?: true
  match_percentage?: true
}

export type MatchResultsMinAggregateInputType = {
  id?: true
  user_id?: true
  job_id?: true
  match_percentage?: true
  recommendation_type?: true
}

export type MatchResultsMaxAggregateInputType = {
  id?: true
  user_id?: true
  job_id?: true
  match_percentage?: true
  recommendation_type?: true
}

export type MatchResultsCountAggregateInputType = {
  id?: true
  user_id?: true
  job_id?: true
  match_percentage?: true
  recommendation_type?: true
  _all?: true
}

export type MatchResultsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MatchResults to aggregate.
   */
  where?: Prisma.MatchResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchResults to fetch.
   */
  orderBy?: Prisma.MatchResultsOrderByWithRelationInput | Prisma.MatchResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MatchResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MatchResults
  **/
  _count?: true | MatchResultsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MatchResultsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MatchResultsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MatchResultsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MatchResultsMaxAggregateInputType
}

export type GetMatchResultsAggregateType<T extends MatchResultsAggregateArgs> = {
      [P in keyof T & keyof AggregateMatchResults]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMatchResults[P]>
    : Prisma.GetScalarType<T[P], AggregateMatchResults[P]>
}




export type MatchResultsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchResultsWhereInput
  orderBy?: Prisma.MatchResultsOrderByWithAggregationInput | Prisma.MatchResultsOrderByWithAggregationInput[]
  by: Prisma.MatchResultsScalarFieldEnum[] | Prisma.MatchResultsScalarFieldEnum
  having?: Prisma.MatchResultsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MatchResultsCountAggregateInputType | true
  _avg?: MatchResultsAvgAggregateInputType
  _sum?: MatchResultsSumAggregateInputType
  _min?: MatchResultsMinAggregateInputType
  _max?: MatchResultsMaxAggregateInputType
}

export type MatchResultsGroupByOutputType = {
  id: number
  user_id: string | null
  job_id: number | null
  match_percentage: runtime.Decimal | null
  recommendation_type: string | null
  _count: MatchResultsCountAggregateOutputType | null
  _avg: MatchResultsAvgAggregateOutputType | null
  _sum: MatchResultsSumAggregateOutputType | null
  _min: MatchResultsMinAggregateOutputType | null
  _max: MatchResultsMaxAggregateOutputType | null
}

type GetMatchResultsGroupByPayload<T extends MatchResultsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MatchResultsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MatchResultsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MatchResultsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MatchResultsGroupByOutputType[P]>
      }
    >
  >



export type MatchResultsWhereInput = {
  AND?: Prisma.MatchResultsWhereInput | Prisma.MatchResultsWhereInput[]
  OR?: Prisma.MatchResultsWhereInput[]
  NOT?: Prisma.MatchResultsWhereInput | Prisma.MatchResultsWhereInput[]
  id?: Prisma.IntFilter<"MatchResults"> | number
  user_id?: Prisma.UuidNullableFilter<"MatchResults"> | string | null
  job_id?: Prisma.IntNullableFilter<"MatchResults"> | number | null
  match_percentage?: Prisma.DecimalNullableFilter<"MatchResults"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.StringNullableFilter<"MatchResults"> | string | null
  jobs?: Prisma.XOR<Prisma.JobsNullableScalarRelationFilter, Prisma.JobsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.UsersWhereInput> | null
}

export type MatchResultsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  job_id?: Prisma.SortOrderInput | Prisma.SortOrder
  match_percentage?: Prisma.SortOrderInput | Prisma.SortOrder
  recommendation_type?: Prisma.SortOrderInput | Prisma.SortOrder
  jobs?: Prisma.JobsOrderByWithRelationInput
  users?: Prisma.UsersOrderByWithRelationInput
}

export type MatchResultsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MatchResultsWhereInput | Prisma.MatchResultsWhereInput[]
  OR?: Prisma.MatchResultsWhereInput[]
  NOT?: Prisma.MatchResultsWhereInput | Prisma.MatchResultsWhereInput[]
  user_id?: Prisma.UuidNullableFilter<"MatchResults"> | string | null
  job_id?: Prisma.IntNullableFilter<"MatchResults"> | number | null
  match_percentage?: Prisma.DecimalNullableFilter<"MatchResults"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.StringNullableFilter<"MatchResults"> | string | null
  jobs?: Prisma.XOR<Prisma.JobsNullableScalarRelationFilter, Prisma.JobsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.UsersWhereInput> | null
}, "id">

export type MatchResultsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  job_id?: Prisma.SortOrderInput | Prisma.SortOrder
  match_percentage?: Prisma.SortOrderInput | Prisma.SortOrder
  recommendation_type?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MatchResultsCountOrderByAggregateInput
  _avg?: Prisma.MatchResultsAvgOrderByAggregateInput
  _max?: Prisma.MatchResultsMaxOrderByAggregateInput
  _min?: Prisma.MatchResultsMinOrderByAggregateInput
  _sum?: Prisma.MatchResultsSumOrderByAggregateInput
}

export type MatchResultsScalarWhereWithAggregatesInput = {
  AND?: Prisma.MatchResultsScalarWhereWithAggregatesInput | Prisma.MatchResultsScalarWhereWithAggregatesInput[]
  OR?: Prisma.MatchResultsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MatchResultsScalarWhereWithAggregatesInput | Prisma.MatchResultsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MatchResults"> | number
  user_id?: Prisma.UuidNullableWithAggregatesFilter<"MatchResults"> | string | null
  job_id?: Prisma.IntNullableWithAggregatesFilter<"MatchResults"> | number | null
  match_percentage?: Prisma.DecimalNullableWithAggregatesFilter<"MatchResults"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.StringNullableWithAggregatesFilter<"MatchResults"> | string | null
}

export type MatchResultsCreateInput = {
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
  jobs?: Prisma.JobsCreateNestedOneWithoutMatch_resultsInput
  users?: Prisma.UsersCreateNestedOneWithoutMatch_resultsInput
}

export type MatchResultsUncheckedCreateInput = {
  id?: number
  user_id?: string | null
  job_id?: number | null
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
}

export type MatchResultsUpdateInput = {
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobs?: Prisma.JobsUpdateOneWithoutMatch_resultsNestedInput
  users?: Prisma.UsersUpdateOneWithoutMatch_resultsNestedInput
}

export type MatchResultsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MatchResultsCreateManyInput = {
  id?: number
  user_id?: string | null
  job_id?: number | null
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
}

export type MatchResultsUpdateManyMutationInput = {
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MatchResultsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MatchResultsListRelationFilter = {
  every?: Prisma.MatchResultsWhereInput
  some?: Prisma.MatchResultsWhereInput
  none?: Prisma.MatchResultsWhereInput
}

export type MatchResultsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MatchResultsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  match_percentage?: Prisma.SortOrder
  recommendation_type?: Prisma.SortOrder
}

export type MatchResultsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  match_percentage?: Prisma.SortOrder
}

export type MatchResultsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  match_percentage?: Prisma.SortOrder
  recommendation_type?: Prisma.SortOrder
}

export type MatchResultsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  match_percentage?: Prisma.SortOrder
  recommendation_type?: Prisma.SortOrder
}

export type MatchResultsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  job_id?: Prisma.SortOrder
  match_percentage?: Prisma.SortOrder
}

export type MatchResultsCreateNestedManyWithoutJobsInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutJobsInput, Prisma.MatchResultsUncheckedCreateWithoutJobsInput> | Prisma.MatchResultsCreateWithoutJobsInput[] | Prisma.MatchResultsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutJobsInput | Prisma.MatchResultsCreateOrConnectWithoutJobsInput[]
  createMany?: Prisma.MatchResultsCreateManyJobsInputEnvelope
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
}

export type MatchResultsUncheckedCreateNestedManyWithoutJobsInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutJobsInput, Prisma.MatchResultsUncheckedCreateWithoutJobsInput> | Prisma.MatchResultsCreateWithoutJobsInput[] | Prisma.MatchResultsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutJobsInput | Prisma.MatchResultsCreateOrConnectWithoutJobsInput[]
  createMany?: Prisma.MatchResultsCreateManyJobsInputEnvelope
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
}

export type MatchResultsUpdateManyWithoutJobsNestedInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutJobsInput, Prisma.MatchResultsUncheckedCreateWithoutJobsInput> | Prisma.MatchResultsCreateWithoutJobsInput[] | Prisma.MatchResultsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutJobsInput | Prisma.MatchResultsCreateOrConnectWithoutJobsInput[]
  upsert?: Prisma.MatchResultsUpsertWithWhereUniqueWithoutJobsInput | Prisma.MatchResultsUpsertWithWhereUniqueWithoutJobsInput[]
  createMany?: Prisma.MatchResultsCreateManyJobsInputEnvelope
  set?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  disconnect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  delete?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  update?: Prisma.MatchResultsUpdateWithWhereUniqueWithoutJobsInput | Prisma.MatchResultsUpdateWithWhereUniqueWithoutJobsInput[]
  updateMany?: Prisma.MatchResultsUpdateManyWithWhereWithoutJobsInput | Prisma.MatchResultsUpdateManyWithWhereWithoutJobsInput[]
  deleteMany?: Prisma.MatchResultsScalarWhereInput | Prisma.MatchResultsScalarWhereInput[]
}

export type MatchResultsUncheckedUpdateManyWithoutJobsNestedInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutJobsInput, Prisma.MatchResultsUncheckedCreateWithoutJobsInput> | Prisma.MatchResultsCreateWithoutJobsInput[] | Prisma.MatchResultsUncheckedCreateWithoutJobsInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutJobsInput | Prisma.MatchResultsCreateOrConnectWithoutJobsInput[]
  upsert?: Prisma.MatchResultsUpsertWithWhereUniqueWithoutJobsInput | Prisma.MatchResultsUpsertWithWhereUniqueWithoutJobsInput[]
  createMany?: Prisma.MatchResultsCreateManyJobsInputEnvelope
  set?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  disconnect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  delete?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  update?: Prisma.MatchResultsUpdateWithWhereUniqueWithoutJobsInput | Prisma.MatchResultsUpdateWithWhereUniqueWithoutJobsInput[]
  updateMany?: Prisma.MatchResultsUpdateManyWithWhereWithoutJobsInput | Prisma.MatchResultsUpdateManyWithWhereWithoutJobsInput[]
  deleteMany?: Prisma.MatchResultsScalarWhereInput | Prisma.MatchResultsScalarWhereInput[]
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type MatchResultsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutUsersInput, Prisma.MatchResultsUncheckedCreateWithoutUsersInput> | Prisma.MatchResultsCreateWithoutUsersInput[] | Prisma.MatchResultsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutUsersInput | Prisma.MatchResultsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.MatchResultsCreateManyUsersInputEnvelope
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
}

export type MatchResultsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutUsersInput, Prisma.MatchResultsUncheckedCreateWithoutUsersInput> | Prisma.MatchResultsCreateWithoutUsersInput[] | Prisma.MatchResultsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutUsersInput | Prisma.MatchResultsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.MatchResultsCreateManyUsersInputEnvelope
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
}

export type MatchResultsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutUsersInput, Prisma.MatchResultsUncheckedCreateWithoutUsersInput> | Prisma.MatchResultsCreateWithoutUsersInput[] | Prisma.MatchResultsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutUsersInput | Prisma.MatchResultsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.MatchResultsUpsertWithWhereUniqueWithoutUsersInput | Prisma.MatchResultsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.MatchResultsCreateManyUsersInputEnvelope
  set?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  disconnect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  delete?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  update?: Prisma.MatchResultsUpdateWithWhereUniqueWithoutUsersInput | Prisma.MatchResultsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.MatchResultsUpdateManyWithWhereWithoutUsersInput | Prisma.MatchResultsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.MatchResultsScalarWhereInput | Prisma.MatchResultsScalarWhereInput[]
}

export type MatchResultsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.MatchResultsCreateWithoutUsersInput, Prisma.MatchResultsUncheckedCreateWithoutUsersInput> | Prisma.MatchResultsCreateWithoutUsersInput[] | Prisma.MatchResultsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MatchResultsCreateOrConnectWithoutUsersInput | Prisma.MatchResultsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.MatchResultsUpsertWithWhereUniqueWithoutUsersInput | Prisma.MatchResultsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.MatchResultsCreateManyUsersInputEnvelope
  set?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  disconnect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  delete?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  connect?: Prisma.MatchResultsWhereUniqueInput | Prisma.MatchResultsWhereUniqueInput[]
  update?: Prisma.MatchResultsUpdateWithWhereUniqueWithoutUsersInput | Prisma.MatchResultsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.MatchResultsUpdateManyWithWhereWithoutUsersInput | Prisma.MatchResultsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.MatchResultsScalarWhereInput | Prisma.MatchResultsScalarWhereInput[]
}

export type MatchResultsCreateWithoutJobsInput = {
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
  users?: Prisma.UsersCreateNestedOneWithoutMatch_resultsInput
}

export type MatchResultsUncheckedCreateWithoutJobsInput = {
  id?: number
  user_id?: string | null
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
}

export type MatchResultsCreateOrConnectWithoutJobsInput = {
  where: Prisma.MatchResultsWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchResultsCreateWithoutJobsInput, Prisma.MatchResultsUncheckedCreateWithoutJobsInput>
}

export type MatchResultsCreateManyJobsInputEnvelope = {
  data: Prisma.MatchResultsCreateManyJobsInput | Prisma.MatchResultsCreateManyJobsInput[]
  skipDuplicates?: boolean
}

export type MatchResultsUpsertWithWhereUniqueWithoutJobsInput = {
  where: Prisma.MatchResultsWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchResultsUpdateWithoutJobsInput, Prisma.MatchResultsUncheckedUpdateWithoutJobsInput>
  create: Prisma.XOR<Prisma.MatchResultsCreateWithoutJobsInput, Prisma.MatchResultsUncheckedCreateWithoutJobsInput>
}

export type MatchResultsUpdateWithWhereUniqueWithoutJobsInput = {
  where: Prisma.MatchResultsWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchResultsUpdateWithoutJobsInput, Prisma.MatchResultsUncheckedUpdateWithoutJobsInput>
}

export type MatchResultsUpdateManyWithWhereWithoutJobsInput = {
  where: Prisma.MatchResultsScalarWhereInput
  data: Prisma.XOR<Prisma.MatchResultsUpdateManyMutationInput, Prisma.MatchResultsUncheckedUpdateManyWithoutJobsInput>
}

export type MatchResultsScalarWhereInput = {
  AND?: Prisma.MatchResultsScalarWhereInput | Prisma.MatchResultsScalarWhereInput[]
  OR?: Prisma.MatchResultsScalarWhereInput[]
  NOT?: Prisma.MatchResultsScalarWhereInput | Prisma.MatchResultsScalarWhereInput[]
  id?: Prisma.IntFilter<"MatchResults"> | number
  user_id?: Prisma.UuidNullableFilter<"MatchResults"> | string | null
  job_id?: Prisma.IntNullableFilter<"MatchResults"> | number | null
  match_percentage?: Prisma.DecimalNullableFilter<"MatchResults"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.StringNullableFilter<"MatchResults"> | string | null
}

export type MatchResultsCreateWithoutUsersInput = {
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
  jobs?: Prisma.JobsCreateNestedOneWithoutMatch_resultsInput
}

export type MatchResultsUncheckedCreateWithoutUsersInput = {
  id?: number
  job_id?: number | null
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
}

export type MatchResultsCreateOrConnectWithoutUsersInput = {
  where: Prisma.MatchResultsWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchResultsCreateWithoutUsersInput, Prisma.MatchResultsUncheckedCreateWithoutUsersInput>
}

export type MatchResultsCreateManyUsersInputEnvelope = {
  data: Prisma.MatchResultsCreateManyUsersInput | Prisma.MatchResultsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type MatchResultsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.MatchResultsWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchResultsUpdateWithoutUsersInput, Prisma.MatchResultsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.MatchResultsCreateWithoutUsersInput, Prisma.MatchResultsUncheckedCreateWithoutUsersInput>
}

export type MatchResultsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.MatchResultsWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchResultsUpdateWithoutUsersInput, Prisma.MatchResultsUncheckedUpdateWithoutUsersInput>
}

export type MatchResultsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.MatchResultsScalarWhereInput
  data: Prisma.XOR<Prisma.MatchResultsUpdateManyMutationInput, Prisma.MatchResultsUncheckedUpdateManyWithoutUsersInput>
}

export type MatchResultsCreateManyJobsInput = {
  id?: number
  user_id?: string | null
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
}

export type MatchResultsUpdateWithoutJobsInput = {
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  users?: Prisma.UsersUpdateOneWithoutMatch_resultsNestedInput
}

export type MatchResultsUncheckedUpdateWithoutJobsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MatchResultsUncheckedUpdateManyWithoutJobsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MatchResultsCreateManyUsersInput = {
  id?: number
  job_id?: number | null
  match_percentage?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: string | null
}

export type MatchResultsUpdateWithoutUsersInput = {
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobs?: Prisma.JobsUpdateOneWithoutMatch_resultsNestedInput
}

export type MatchResultsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MatchResultsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  job_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  match_percentage?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  recommendation_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type MatchResultsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  match_percentage?: boolean
  recommendation_type?: boolean
  jobs?: boolean | Prisma.MatchResults$jobsArgs<ExtArgs>
  users?: boolean | Prisma.MatchResults$usersArgs<ExtArgs>
}, ExtArgs["result"]["matchResults"]>

export type MatchResultsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  match_percentage?: boolean
  recommendation_type?: boolean
  jobs?: boolean | Prisma.MatchResults$jobsArgs<ExtArgs>
  users?: boolean | Prisma.MatchResults$usersArgs<ExtArgs>
}, ExtArgs["result"]["matchResults"]>

export type MatchResultsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  match_percentage?: boolean
  recommendation_type?: boolean
  jobs?: boolean | Prisma.MatchResults$jobsArgs<ExtArgs>
  users?: boolean | Prisma.MatchResults$usersArgs<ExtArgs>
}, ExtArgs["result"]["matchResults"]>

export type MatchResultsSelectScalar = {
  id?: boolean
  user_id?: boolean
  job_id?: boolean
  match_percentage?: boolean
  recommendation_type?: boolean
}

export type MatchResultsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "job_id" | "match_percentage" | "recommendation_type", ExtArgs["result"]["matchResults"]>
export type MatchResultsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.MatchResults$jobsArgs<ExtArgs>
  users?: boolean | Prisma.MatchResults$usersArgs<ExtArgs>
}
export type MatchResultsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.MatchResults$jobsArgs<ExtArgs>
  users?: boolean | Prisma.MatchResults$usersArgs<ExtArgs>
}
export type MatchResultsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobs?: boolean | Prisma.MatchResults$jobsArgs<ExtArgs>
  users?: boolean | Prisma.MatchResults$usersArgs<ExtArgs>
}

export type $MatchResultsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MatchResults"
  objects: {
    jobs: Prisma.$JobsPayload<ExtArgs> | null
    users: Prisma.$UsersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: string | null
    job_id: number | null
    match_percentage: runtime.Decimal | null
    recommendation_type: string | null
  }, ExtArgs["result"]["matchResults"]>
  composites: {}
}

export type MatchResultsGetPayload<S extends boolean | null | undefined | MatchResultsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload, S>

export type MatchResultsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MatchResultsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MatchResultsCountAggregateInputType | true
  }

export interface MatchResultsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MatchResults'], meta: { name: 'MatchResults' } }
  /**
   * Find zero or one MatchResults that matches the filter.
   * @param {MatchResultsFindUniqueArgs} args - Arguments to find a MatchResults
   * @example
   * // Get one MatchResults
   * const matchResults = await prisma.matchResults.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MatchResultsFindUniqueArgs>(args: Prisma.SelectSubset<T, MatchResultsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MatchResults that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MatchResultsFindUniqueOrThrowArgs} args - Arguments to find a MatchResults
   * @example
   * // Get one MatchResults
   * const matchResults = await prisma.matchResults.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MatchResultsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MatchResultsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MatchResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchResultsFindFirstArgs} args - Arguments to find a MatchResults
   * @example
   * // Get one MatchResults
   * const matchResults = await prisma.matchResults.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MatchResultsFindFirstArgs>(args?: Prisma.SelectSubset<T, MatchResultsFindFirstArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MatchResults that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchResultsFindFirstOrThrowArgs} args - Arguments to find a MatchResults
   * @example
   * // Get one MatchResults
   * const matchResults = await prisma.matchResults.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MatchResultsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MatchResultsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MatchResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchResultsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MatchResults
   * const matchResults = await prisma.matchResults.findMany()
   * 
   * // Get first 10 MatchResults
   * const matchResults = await prisma.matchResults.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const matchResultsWithIdOnly = await prisma.matchResults.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MatchResultsFindManyArgs>(args?: Prisma.SelectSubset<T, MatchResultsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MatchResults.
   * @param {MatchResultsCreateArgs} args - Arguments to create a MatchResults.
   * @example
   * // Create one MatchResults
   * const MatchResults = await prisma.matchResults.create({
   *   data: {
   *     // ... data to create a MatchResults
   *   }
   * })
   * 
   */
  create<T extends MatchResultsCreateArgs>(args: Prisma.SelectSubset<T, MatchResultsCreateArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MatchResults.
   * @param {MatchResultsCreateManyArgs} args - Arguments to create many MatchResults.
   * @example
   * // Create many MatchResults
   * const matchResults = await prisma.matchResults.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MatchResultsCreateManyArgs>(args?: Prisma.SelectSubset<T, MatchResultsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MatchResults and returns the data saved in the database.
   * @param {MatchResultsCreateManyAndReturnArgs} args - Arguments to create many MatchResults.
   * @example
   * // Create many MatchResults
   * const matchResults = await prisma.matchResults.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MatchResults and only return the `id`
   * const matchResultsWithIdOnly = await prisma.matchResults.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MatchResultsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MatchResultsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MatchResults.
   * @param {MatchResultsDeleteArgs} args - Arguments to delete one MatchResults.
   * @example
   * // Delete one MatchResults
   * const MatchResults = await prisma.matchResults.delete({
   *   where: {
   *     // ... filter to delete one MatchResults
   *   }
   * })
   * 
   */
  delete<T extends MatchResultsDeleteArgs>(args: Prisma.SelectSubset<T, MatchResultsDeleteArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MatchResults.
   * @param {MatchResultsUpdateArgs} args - Arguments to update one MatchResults.
   * @example
   * // Update one MatchResults
   * const matchResults = await prisma.matchResults.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MatchResultsUpdateArgs>(args: Prisma.SelectSubset<T, MatchResultsUpdateArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MatchResults.
   * @param {MatchResultsDeleteManyArgs} args - Arguments to filter MatchResults to delete.
   * @example
   * // Delete a few MatchResults
   * const { count } = await prisma.matchResults.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MatchResultsDeleteManyArgs>(args?: Prisma.SelectSubset<T, MatchResultsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MatchResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchResultsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MatchResults
   * const matchResults = await prisma.matchResults.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MatchResultsUpdateManyArgs>(args: Prisma.SelectSubset<T, MatchResultsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MatchResults and returns the data updated in the database.
   * @param {MatchResultsUpdateManyAndReturnArgs} args - Arguments to update many MatchResults.
   * @example
   * // Update many MatchResults
   * const matchResults = await prisma.matchResults.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MatchResults and only return the `id`
   * const matchResultsWithIdOnly = await prisma.matchResults.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MatchResultsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MatchResultsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MatchResults.
   * @param {MatchResultsUpsertArgs} args - Arguments to update or create a MatchResults.
   * @example
   * // Update or create a MatchResults
   * const matchResults = await prisma.matchResults.upsert({
   *   create: {
   *     // ... data to create a MatchResults
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MatchResults we want to update
   *   }
   * })
   */
  upsert<T extends MatchResultsUpsertArgs>(args: Prisma.SelectSubset<T, MatchResultsUpsertArgs<ExtArgs>>): Prisma.Prisma__MatchResultsClient<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MatchResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchResultsCountArgs} args - Arguments to filter MatchResults to count.
   * @example
   * // Count the number of MatchResults
   * const count = await prisma.matchResults.count({
   *   where: {
   *     // ... the filter for the MatchResults we want to count
   *   }
   * })
  **/
  count<T extends MatchResultsCountArgs>(
    args?: Prisma.Subset<T, MatchResultsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MatchResultsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MatchResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchResultsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MatchResultsAggregateArgs>(args: Prisma.Subset<T, MatchResultsAggregateArgs>): Prisma.PrismaPromise<GetMatchResultsAggregateType<T>>

  /**
   * Group by MatchResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchResultsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MatchResultsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MatchResultsGroupByArgs['orderBy'] }
      : { orderBy?: MatchResultsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MatchResultsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMatchResultsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MatchResults model
 */
readonly fields: MatchResultsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MatchResults.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MatchResultsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  jobs<T extends Prisma.MatchResults$jobsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MatchResults$jobsArgs<ExtArgs>>): Prisma.Prisma__JobsClient<runtime.Types.Result.GetResult<Prisma.$JobsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.MatchResults$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MatchResults$usersArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MatchResults model
 */
export interface MatchResultsFieldRefs {
  readonly id: Prisma.FieldRef<"MatchResults", 'Int'>
  readonly user_id: Prisma.FieldRef<"MatchResults", 'String'>
  readonly job_id: Prisma.FieldRef<"MatchResults", 'Int'>
  readonly match_percentage: Prisma.FieldRef<"MatchResults", 'Decimal'>
  readonly recommendation_type: Prisma.FieldRef<"MatchResults", 'String'>
}
    

// Custom InputTypes
/**
 * MatchResults findUnique
 */
export type MatchResultsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * Filter, which MatchResults to fetch.
   */
  where: Prisma.MatchResultsWhereUniqueInput
}

/**
 * MatchResults findUniqueOrThrow
 */
export type MatchResultsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * Filter, which MatchResults to fetch.
   */
  where: Prisma.MatchResultsWhereUniqueInput
}

/**
 * MatchResults findFirst
 */
export type MatchResultsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * Filter, which MatchResults to fetch.
   */
  where?: Prisma.MatchResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchResults to fetch.
   */
  orderBy?: Prisma.MatchResultsOrderByWithRelationInput | Prisma.MatchResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MatchResults.
   */
  cursor?: Prisma.MatchResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MatchResults.
   */
  distinct?: Prisma.MatchResultsScalarFieldEnum | Prisma.MatchResultsScalarFieldEnum[]
}

/**
 * MatchResults findFirstOrThrow
 */
export type MatchResultsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * Filter, which MatchResults to fetch.
   */
  where?: Prisma.MatchResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchResults to fetch.
   */
  orderBy?: Prisma.MatchResultsOrderByWithRelationInput | Prisma.MatchResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MatchResults.
   */
  cursor?: Prisma.MatchResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MatchResults.
   */
  distinct?: Prisma.MatchResultsScalarFieldEnum | Prisma.MatchResultsScalarFieldEnum[]
}

/**
 * MatchResults findMany
 */
export type MatchResultsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * Filter, which MatchResults to fetch.
   */
  where?: Prisma.MatchResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchResults to fetch.
   */
  orderBy?: Prisma.MatchResultsOrderByWithRelationInput | Prisma.MatchResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MatchResults.
   */
  cursor?: Prisma.MatchResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchResults.
   */
  skip?: number
  distinct?: Prisma.MatchResultsScalarFieldEnum | Prisma.MatchResultsScalarFieldEnum[]
}

/**
 * MatchResults create
 */
export type MatchResultsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * The data needed to create a MatchResults.
   */
  data?: Prisma.XOR<Prisma.MatchResultsCreateInput, Prisma.MatchResultsUncheckedCreateInput>
}

/**
 * MatchResults createMany
 */
export type MatchResultsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MatchResults.
   */
  data: Prisma.MatchResultsCreateManyInput | Prisma.MatchResultsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MatchResults createManyAndReturn
 */
export type MatchResultsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * The data used to create many MatchResults.
   */
  data: Prisma.MatchResultsCreateManyInput | Prisma.MatchResultsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MatchResults update
 */
export type MatchResultsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * The data needed to update a MatchResults.
   */
  data: Prisma.XOR<Prisma.MatchResultsUpdateInput, Prisma.MatchResultsUncheckedUpdateInput>
  /**
   * Choose, which MatchResults to update.
   */
  where: Prisma.MatchResultsWhereUniqueInput
}

/**
 * MatchResults updateMany
 */
export type MatchResultsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MatchResults.
   */
  data: Prisma.XOR<Prisma.MatchResultsUpdateManyMutationInput, Prisma.MatchResultsUncheckedUpdateManyInput>
  /**
   * Filter which MatchResults to update
   */
  where?: Prisma.MatchResultsWhereInput
  /**
   * Limit how many MatchResults to update.
   */
  limit?: number
}

/**
 * MatchResults updateManyAndReturn
 */
export type MatchResultsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * The data used to update MatchResults.
   */
  data: Prisma.XOR<Prisma.MatchResultsUpdateManyMutationInput, Prisma.MatchResultsUncheckedUpdateManyInput>
  /**
   * Filter which MatchResults to update
   */
  where?: Prisma.MatchResultsWhereInput
  /**
   * Limit how many MatchResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MatchResults upsert
 */
export type MatchResultsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * The filter to search for the MatchResults to update in case it exists.
   */
  where: Prisma.MatchResultsWhereUniqueInput
  /**
   * In case the MatchResults found by the `where` argument doesn't exist, create a new MatchResults with this data.
   */
  create: Prisma.XOR<Prisma.MatchResultsCreateInput, Prisma.MatchResultsUncheckedCreateInput>
  /**
   * In case the MatchResults was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MatchResultsUpdateInput, Prisma.MatchResultsUncheckedUpdateInput>
}

/**
 * MatchResults delete
 */
export type MatchResultsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  /**
   * Filter which MatchResults to delete.
   */
  where: Prisma.MatchResultsWhereUniqueInput
}

/**
 * MatchResults deleteMany
 */
export type MatchResultsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MatchResults to delete
   */
  where?: Prisma.MatchResultsWhereInput
  /**
   * Limit how many MatchResults to delete.
   */
  limit?: number
}

/**
 * MatchResults.jobs
 */
export type MatchResults$jobsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Jobs
   */
  select?: Prisma.JobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Jobs
   */
  omit?: Prisma.JobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobsInclude<ExtArgs> | null
  where?: Prisma.JobsWhereInput
}

/**
 * MatchResults.users
 */
export type MatchResults$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  where?: Prisma.UsersWhereInput
}

/**
 * MatchResults without action
 */
export type MatchResultsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
}
