
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Users` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Users
 * 
 */
export type UsersModel = runtime.Types.Result.DefaultSelection<Prisma.$UsersPayload>

export type AggregateUsers = {
  _count: UsersCountAggregateOutputType | null
  _avg: UsersAvgAggregateOutputType | null
  _sum: UsersSumAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

export type UsersAvgAggregateOutputType = {
  role_id: number | null
}

export type UsersSumAggregateOutputType = {
  role_id: number | null
}

export type UsersMinAggregateOutputType = {
  id: string | null
  role_id: number | null
  full_name: string | null
  email: string | null
  password: string | null
  bio: string | null
  is_verified: boolean | null
}

export type UsersMaxAggregateOutputType = {
  id: string | null
  role_id: number | null
  full_name: string | null
  email: string | null
  password: string | null
  bio: string | null
  is_verified: boolean | null
}

export type UsersCountAggregateOutputType = {
  id: number
  role_id: number
  full_name: number
  email: number
  password: number
  bio: number
  is_verified: number
  _all: number
}


export type UsersAvgAggregateInputType = {
  role_id?: true
}

export type UsersSumAggregateInputType = {
  role_id?: true
}

export type UsersMinAggregateInputType = {
  id?: true
  role_id?: true
  full_name?: true
  email?: true
  password?: true
  bio?: true
  is_verified?: true
}

export type UsersMaxAggregateInputType = {
  id?: true
  role_id?: true
  full_name?: true
  email?: true
  password?: true
  bio?: true
  is_verified?: true
}

export type UsersCountAggregateInputType = {
  id?: true
  role_id?: true
  full_name?: true
  email?: true
  password?: true
  bio?: true
  is_verified?: true
  _all?: true
}

export type UsersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to aggregate.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UsersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UsersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UsersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsersMaxAggregateInputType
}

export type GetUsersAggregateType<T extends UsersAggregateArgs> = {
      [P in keyof T & keyof AggregateUsers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsers[P]>
    : Prisma.GetScalarType<T[P], AggregateUsers[P]>
}




export type UsersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsersWhereInput
  orderBy?: Prisma.UsersOrderByWithAggregationInput | Prisma.UsersOrderByWithAggregationInput[]
  by: Prisma.UsersScalarFieldEnum[] | Prisma.UsersScalarFieldEnum
  having?: Prisma.UsersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsersCountAggregateInputType | true
  _avg?: UsersAvgAggregateInputType
  _sum?: UsersSumAggregateInputType
  _min?: UsersMinAggregateInputType
  _max?: UsersMaxAggregateInputType
}

export type UsersGroupByOutputType = {
  id: string
  role_id: number | null
  full_name: string
  email: string
  password: string
  bio: string | null
  is_verified: boolean | null
  _count: UsersCountAggregateOutputType | null
  _avg: UsersAvgAggregateOutputType | null
  _sum: UsersSumAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

type GetUsersGroupByPayload<T extends UsersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
      }
    >
  >



export type UsersWhereInput = {
  AND?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  OR?: Prisma.UsersWhereInput[]
  NOT?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  id?: Prisma.UuidFilter<"Users"> | string
  role_id?: Prisma.IntNullableFilter<"Users"> | number | null
  full_name?: Prisma.StringFilter<"Users"> | string
  email?: Prisma.StringFilter<"Users"> | string
  password?: Prisma.StringFilter<"Users"> | string
  bio?: Prisma.StringNullableFilter<"Users"> | string | null
  is_verified?: Prisma.BoolNullableFilter<"Users"> | boolean | null
  applications?: Prisma.ApplicationsListRelationFilter
  companies?: Prisma.CompaniesListRelationFilter
  match_results?: Prisma.MatchResultsListRelationFilter
  user_badges?: Prisma.UserBadgesListRelationFilter
  user_educations?: Prisma.UserEducationsListRelationFilter
  user_skills?: Prisma.UserSkillsListRelationFilter
  roles?: Prisma.XOR<Prisma.RolesNullableScalarRelationFilter, Prisma.RolesWhereInput> | null
}

export type UsersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  role_id?: Prisma.SortOrderInput | Prisma.SortOrder
  full_name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  is_verified?: Prisma.SortOrderInput | Prisma.SortOrder
  applications?: Prisma.ApplicationsOrderByRelationAggregateInput
  companies?: Prisma.CompaniesOrderByRelationAggregateInput
  match_results?: Prisma.MatchResultsOrderByRelationAggregateInput
  user_badges?: Prisma.UserBadgesOrderByRelationAggregateInput
  user_educations?: Prisma.UserEducationsOrderByRelationAggregateInput
  user_skills?: Prisma.UserSkillsOrderByRelationAggregateInput
  roles?: Prisma.RolesOrderByWithRelationInput
}

export type UsersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  OR?: Prisma.UsersWhereInput[]
  NOT?: Prisma.UsersWhereInput | Prisma.UsersWhereInput[]
  role_id?: Prisma.IntNullableFilter<"Users"> | number | null
  full_name?: Prisma.StringFilter<"Users"> | string
  password?: Prisma.StringFilter<"Users"> | string
  bio?: Prisma.StringNullableFilter<"Users"> | string | null
  is_verified?: Prisma.BoolNullableFilter<"Users"> | boolean | null
  applications?: Prisma.ApplicationsListRelationFilter
  companies?: Prisma.CompaniesListRelationFilter
  match_results?: Prisma.MatchResultsListRelationFilter
  user_badges?: Prisma.UserBadgesListRelationFilter
  user_educations?: Prisma.UserEducationsListRelationFilter
  user_skills?: Prisma.UserSkillsListRelationFilter
  roles?: Prisma.XOR<Prisma.RolesNullableScalarRelationFilter, Prisma.RolesWhereInput> | null
}, "id" | "email">

export type UsersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  role_id?: Prisma.SortOrderInput | Prisma.SortOrder
  full_name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  is_verified?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UsersCountOrderByAggregateInput
  _avg?: Prisma.UsersAvgOrderByAggregateInput
  _max?: Prisma.UsersMaxOrderByAggregateInput
  _min?: Prisma.UsersMinOrderByAggregateInput
  _sum?: Prisma.UsersSumOrderByAggregateInput
}

export type UsersScalarWhereWithAggregatesInput = {
  AND?: Prisma.UsersScalarWhereWithAggregatesInput | Prisma.UsersScalarWhereWithAggregatesInput[]
  OR?: Prisma.UsersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UsersScalarWhereWithAggregatesInput | Prisma.UsersScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Users"> | string
  role_id?: Prisma.IntNullableWithAggregatesFilter<"Users"> | number | null
  full_name?: Prisma.StringWithAggregatesFilter<"Users"> | string
  email?: Prisma.StringWithAggregatesFilter<"Users"> | string
  password?: Prisma.StringWithAggregatesFilter<"Users"> | string
  bio?: Prisma.StringNullableWithAggregatesFilter<"Users"> | string | null
  is_verified?: Prisma.BoolNullableWithAggregatesFilter<"Users"> | boolean | null
}

export type UsersCreateInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsCreateNestedManyWithoutUsersInput
  roles?: Prisma.RolesCreateNestedOneWithoutUsersInput
}

export type UsersUncheckedCreateInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsUncheckedCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesUncheckedCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsUncheckedCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesUncheckedCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsUncheckedCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUpdateManyWithoutUsersNestedInput
  roles?: Prisma.RolesUpdateOneWithoutUsersNestedInput
}

export type UsersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUncheckedUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUncheckedUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUncheckedUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUncheckedUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUncheckedUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateManyInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
}

export type UsersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UsersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type UsersNullableScalarRelationFilter = {
  is?: Prisma.UsersWhereInput | null
  isNot?: Prisma.UsersWhereInput | null
}

export type UsersListRelationFilter = {
  every?: Prisma.UsersWhereInput
  some?: Prisma.UsersWhereInput
  none?: Prisma.UsersWhereInput
}

export type UsersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UsersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  full_name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
}

export type UsersAvgOrderByAggregateInput = {
  role_id?: Prisma.SortOrder
}

export type UsersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  full_name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
}

export type UsersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  full_name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
}

export type UsersSumOrderByAggregateInput = {
  role_id?: Prisma.SortOrder
}

export type UsersCreateNestedOneWithoutApplicationsInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutApplicationsInput, Prisma.UsersUncheckedCreateWithoutApplicationsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutApplicationsInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneWithoutApplicationsNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutApplicationsInput, Prisma.UsersUncheckedCreateWithoutApplicationsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutApplicationsInput
  upsert?: Prisma.UsersUpsertWithoutApplicationsInput
  disconnect?: Prisma.UsersWhereInput | boolean
  delete?: Prisma.UsersWhereInput | boolean
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutApplicationsInput, Prisma.UsersUpdateWithoutApplicationsInput>, Prisma.UsersUncheckedUpdateWithoutApplicationsInput>
}

export type UsersCreateNestedOneWithoutCompaniesInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutCompaniesInput, Prisma.UsersUncheckedCreateWithoutCompaniesInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutCompaniesInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneWithoutCompaniesNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutCompaniesInput, Prisma.UsersUncheckedCreateWithoutCompaniesInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutCompaniesInput
  upsert?: Prisma.UsersUpsertWithoutCompaniesInput
  disconnect?: Prisma.UsersWhereInput | boolean
  delete?: Prisma.UsersWhereInput | boolean
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutCompaniesInput, Prisma.UsersUpdateWithoutCompaniesInput>, Prisma.UsersUncheckedUpdateWithoutCompaniesInput>
}

export type UsersCreateNestedOneWithoutMatch_resultsInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutMatch_resultsInput, Prisma.UsersUncheckedCreateWithoutMatch_resultsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutMatch_resultsInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneWithoutMatch_resultsNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutMatch_resultsInput, Prisma.UsersUncheckedCreateWithoutMatch_resultsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutMatch_resultsInput
  upsert?: Prisma.UsersUpsertWithoutMatch_resultsInput
  disconnect?: Prisma.UsersWhereInput | boolean
  delete?: Prisma.UsersWhereInput | boolean
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutMatch_resultsInput, Prisma.UsersUpdateWithoutMatch_resultsInput>, Prisma.UsersUncheckedUpdateWithoutMatch_resultsInput>
}

export type UsersCreateNestedManyWithoutRolesInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutRolesInput, Prisma.UsersUncheckedCreateWithoutRolesInput> | Prisma.UsersCreateWithoutRolesInput[] | Prisma.UsersUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutRolesInput | Prisma.UsersCreateOrConnectWithoutRolesInput[]
  createMany?: Prisma.UsersCreateManyRolesInputEnvelope
  connect?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
}

export type UsersUncheckedCreateNestedManyWithoutRolesInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutRolesInput, Prisma.UsersUncheckedCreateWithoutRolesInput> | Prisma.UsersCreateWithoutRolesInput[] | Prisma.UsersUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutRolesInput | Prisma.UsersCreateOrConnectWithoutRolesInput[]
  createMany?: Prisma.UsersCreateManyRolesInputEnvelope
  connect?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
}

export type UsersUpdateManyWithoutRolesNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutRolesInput, Prisma.UsersUncheckedCreateWithoutRolesInput> | Prisma.UsersCreateWithoutRolesInput[] | Prisma.UsersUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutRolesInput | Prisma.UsersCreateOrConnectWithoutRolesInput[]
  upsert?: Prisma.UsersUpsertWithWhereUniqueWithoutRolesInput | Prisma.UsersUpsertWithWhereUniqueWithoutRolesInput[]
  createMany?: Prisma.UsersCreateManyRolesInputEnvelope
  set?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  disconnect?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  delete?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  connect?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  update?: Prisma.UsersUpdateWithWhereUniqueWithoutRolesInput | Prisma.UsersUpdateWithWhereUniqueWithoutRolesInput[]
  updateMany?: Prisma.UsersUpdateManyWithWhereWithoutRolesInput | Prisma.UsersUpdateManyWithWhereWithoutRolesInput[]
  deleteMany?: Prisma.UsersScalarWhereInput | Prisma.UsersScalarWhereInput[]
}

export type UsersUncheckedUpdateManyWithoutRolesNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutRolesInput, Prisma.UsersUncheckedCreateWithoutRolesInput> | Prisma.UsersCreateWithoutRolesInput[] | Prisma.UsersUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutRolesInput | Prisma.UsersCreateOrConnectWithoutRolesInput[]
  upsert?: Prisma.UsersUpsertWithWhereUniqueWithoutRolesInput | Prisma.UsersUpsertWithWhereUniqueWithoutRolesInput[]
  createMany?: Prisma.UsersCreateManyRolesInputEnvelope
  set?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  disconnect?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  delete?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  connect?: Prisma.UsersWhereUniqueInput | Prisma.UsersWhereUniqueInput[]
  update?: Prisma.UsersUpdateWithWhereUniqueWithoutRolesInput | Prisma.UsersUpdateWithWhereUniqueWithoutRolesInput[]
  updateMany?: Prisma.UsersUpdateManyWithWhereWithoutRolesInput | Prisma.UsersUpdateManyWithWhereWithoutRolesInput[]
  deleteMany?: Prisma.UsersScalarWhereInput | Prisma.UsersScalarWhereInput[]
}

export type UsersCreateNestedOneWithoutUser_badgesInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutUser_badgesInput, Prisma.UsersUncheckedCreateWithoutUser_badgesInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutUser_badgesInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneWithoutUser_badgesNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutUser_badgesInput, Prisma.UsersUncheckedCreateWithoutUser_badgesInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutUser_badgesInput
  upsert?: Prisma.UsersUpsertWithoutUser_badgesInput
  disconnect?: Prisma.UsersWhereInput | boolean
  delete?: Prisma.UsersWhereInput | boolean
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutUser_badgesInput, Prisma.UsersUpdateWithoutUser_badgesInput>, Prisma.UsersUncheckedUpdateWithoutUser_badgesInput>
}

export type UsersCreateNestedOneWithoutUser_educationsInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutUser_educationsInput, Prisma.UsersUncheckedCreateWithoutUser_educationsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutUser_educationsInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneWithoutUser_educationsNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutUser_educationsInput, Prisma.UsersUncheckedCreateWithoutUser_educationsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutUser_educationsInput
  upsert?: Prisma.UsersUpsertWithoutUser_educationsInput
  disconnect?: Prisma.UsersWhereInput | boolean
  delete?: Prisma.UsersWhereInput | boolean
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutUser_educationsInput, Prisma.UsersUpdateWithoutUser_educationsInput>, Prisma.UsersUncheckedUpdateWithoutUser_educationsInput>
}

export type UsersCreateNestedOneWithoutUser_skillsInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutUser_skillsInput, Prisma.UsersUncheckedCreateWithoutUser_skillsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutUser_skillsInput
  connect?: Prisma.UsersWhereUniqueInput
}

export type UsersUpdateOneWithoutUser_skillsNestedInput = {
  create?: Prisma.XOR<Prisma.UsersCreateWithoutUser_skillsInput, Prisma.UsersUncheckedCreateWithoutUser_skillsInput>
  connectOrCreate?: Prisma.UsersCreateOrConnectWithoutUser_skillsInput
  upsert?: Prisma.UsersUpsertWithoutUser_skillsInput
  disconnect?: Prisma.UsersWhereInput | boolean
  delete?: Prisma.UsersWhereInput | boolean
  connect?: Prisma.UsersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsersUpdateToOneWithWhereWithoutUser_skillsInput, Prisma.UsersUpdateWithoutUser_skillsInput>, Prisma.UsersUncheckedUpdateWithoutUser_skillsInput>
}

export type UsersCreateWithoutApplicationsInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  companies?: Prisma.CompaniesCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsCreateNestedManyWithoutUsersInput
  roles?: Prisma.RolesCreateNestedOneWithoutUsersInput
}

export type UsersUncheckedCreateWithoutApplicationsInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  companies?: Prisma.CompaniesUncheckedCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsUncheckedCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesUncheckedCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsUncheckedCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutApplicationsInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutApplicationsInput, Prisma.UsersUncheckedCreateWithoutApplicationsInput>
}

export type UsersUpsertWithoutApplicationsInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutApplicationsInput, Prisma.UsersUncheckedUpdateWithoutApplicationsInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutApplicationsInput, Prisma.UsersUncheckedCreateWithoutApplicationsInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutApplicationsInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutApplicationsInput, Prisma.UsersUncheckedUpdateWithoutApplicationsInput>
}

export type UsersUpdateWithoutApplicationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  companies?: Prisma.CompaniesUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUpdateManyWithoutUsersNestedInput
  roles?: Prisma.RolesUpdateOneWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutApplicationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  companies?: Prisma.CompaniesUncheckedUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUncheckedUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUncheckedUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUncheckedUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateWithoutCompaniesInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsCreateNestedManyWithoutUsersInput
  roles?: Prisma.RolesCreateNestedOneWithoutUsersInput
}

export type UsersUncheckedCreateWithoutCompaniesInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsUncheckedCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsUncheckedCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesUncheckedCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsUncheckedCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutCompaniesInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutCompaniesInput, Prisma.UsersUncheckedCreateWithoutCompaniesInput>
}

export type UsersUpsertWithoutCompaniesInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutCompaniesInput, Prisma.UsersUncheckedUpdateWithoutCompaniesInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutCompaniesInput, Prisma.UsersUncheckedCreateWithoutCompaniesInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutCompaniesInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutCompaniesInput, Prisma.UsersUncheckedUpdateWithoutCompaniesInput>
}

export type UsersUpdateWithoutCompaniesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUpdateManyWithoutUsersNestedInput
  roles?: Prisma.RolesUpdateOneWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutCompaniesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUncheckedUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUncheckedUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUncheckedUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUncheckedUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateWithoutMatch_resultsInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsCreateNestedManyWithoutUsersInput
  roles?: Prisma.RolesCreateNestedOneWithoutUsersInput
}

export type UsersUncheckedCreateWithoutMatch_resultsInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsUncheckedCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesUncheckedCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesUncheckedCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsUncheckedCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutMatch_resultsInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutMatch_resultsInput, Prisma.UsersUncheckedCreateWithoutMatch_resultsInput>
}

export type UsersUpsertWithoutMatch_resultsInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutMatch_resultsInput, Prisma.UsersUncheckedUpdateWithoutMatch_resultsInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutMatch_resultsInput, Prisma.UsersUncheckedCreateWithoutMatch_resultsInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutMatch_resultsInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutMatch_resultsInput, Prisma.UsersUncheckedUpdateWithoutMatch_resultsInput>
}

export type UsersUpdateWithoutMatch_resultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUpdateManyWithoutUsersNestedInput
  roles?: Prisma.RolesUpdateOneWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutMatch_resultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUncheckedUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUncheckedUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUncheckedUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUncheckedUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateWithoutRolesInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsCreateNestedManyWithoutUsersInput
}

export type UsersUncheckedCreateWithoutRolesInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsUncheckedCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesUncheckedCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsUncheckedCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesUncheckedCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsUncheckedCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutRolesInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutRolesInput, Prisma.UsersUncheckedCreateWithoutRolesInput>
}

export type UsersCreateManyRolesInputEnvelope = {
  data: Prisma.UsersCreateManyRolesInput | Prisma.UsersCreateManyRolesInput[]
  skipDuplicates?: boolean
}

export type UsersUpsertWithWhereUniqueWithoutRolesInput = {
  where: Prisma.UsersWhereUniqueInput
  update: Prisma.XOR<Prisma.UsersUpdateWithoutRolesInput, Prisma.UsersUncheckedUpdateWithoutRolesInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutRolesInput, Prisma.UsersUncheckedCreateWithoutRolesInput>
}

export type UsersUpdateWithWhereUniqueWithoutRolesInput = {
  where: Prisma.UsersWhereUniqueInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutRolesInput, Prisma.UsersUncheckedUpdateWithoutRolesInput>
}

export type UsersUpdateManyWithWhereWithoutRolesInput = {
  where: Prisma.UsersScalarWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateManyMutationInput, Prisma.UsersUncheckedUpdateManyWithoutRolesInput>
}

export type UsersScalarWhereInput = {
  AND?: Prisma.UsersScalarWhereInput | Prisma.UsersScalarWhereInput[]
  OR?: Prisma.UsersScalarWhereInput[]
  NOT?: Prisma.UsersScalarWhereInput | Prisma.UsersScalarWhereInput[]
  id?: Prisma.UuidFilter<"Users"> | string
  role_id?: Prisma.IntNullableFilter<"Users"> | number | null
  full_name?: Prisma.StringFilter<"Users"> | string
  email?: Prisma.StringFilter<"Users"> | string
  password?: Prisma.StringFilter<"Users"> | string
  bio?: Prisma.StringNullableFilter<"Users"> | string | null
  is_verified?: Prisma.BoolNullableFilter<"Users"> | boolean | null
}

export type UsersCreateWithoutUser_badgesInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsCreateNestedManyWithoutUsersInput
  roles?: Prisma.RolesCreateNestedOneWithoutUsersInput
}

export type UsersUncheckedCreateWithoutUser_badgesInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsUncheckedCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesUncheckedCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsUncheckedCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsUncheckedCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutUser_badgesInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutUser_badgesInput, Prisma.UsersUncheckedCreateWithoutUser_badgesInput>
}

export type UsersUpsertWithoutUser_badgesInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutUser_badgesInput, Prisma.UsersUncheckedUpdateWithoutUser_badgesInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutUser_badgesInput, Prisma.UsersUncheckedCreateWithoutUser_badgesInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutUser_badgesInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutUser_badgesInput, Prisma.UsersUncheckedUpdateWithoutUser_badgesInput>
}

export type UsersUpdateWithoutUser_badgesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUpdateManyWithoutUsersNestedInput
  roles?: Prisma.RolesUpdateOneWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutUser_badgesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUncheckedUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUncheckedUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUncheckedUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUncheckedUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateWithoutUser_educationsInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsCreateNestedManyWithoutUsersInput
  roles?: Prisma.RolesCreateNestedOneWithoutUsersInput
}

export type UsersUncheckedCreateWithoutUser_educationsInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsUncheckedCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesUncheckedCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsUncheckedCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesUncheckedCreateNestedManyWithoutUsersInput
  user_skills?: Prisma.UserSkillsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutUser_educationsInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutUser_educationsInput, Prisma.UsersUncheckedCreateWithoutUser_educationsInput>
}

export type UsersUpsertWithoutUser_educationsInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutUser_educationsInput, Prisma.UsersUncheckedUpdateWithoutUser_educationsInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutUser_educationsInput, Prisma.UsersUncheckedCreateWithoutUser_educationsInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutUser_educationsInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutUser_educationsInput, Prisma.UsersUncheckedUpdateWithoutUser_educationsInput>
}

export type UsersUpdateWithoutUser_educationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUpdateManyWithoutUsersNestedInput
  roles?: Prisma.RolesUpdateOneWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutUser_educationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUncheckedUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUncheckedUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUncheckedUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUncheckedUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateWithoutUser_skillsInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsCreateNestedManyWithoutUsersInput
  roles?: Prisma.RolesCreateNestedOneWithoutUsersInput
}

export type UsersUncheckedCreateWithoutUser_skillsInput = {
  id?: string
  role_id?: number | null
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
  applications?: Prisma.ApplicationsUncheckedCreateNestedManyWithoutUsersInput
  companies?: Prisma.CompaniesUncheckedCreateNestedManyWithoutUsersInput
  match_results?: Prisma.MatchResultsUncheckedCreateNestedManyWithoutUsersInput
  user_badges?: Prisma.UserBadgesUncheckedCreateNestedManyWithoutUsersInput
  user_educations?: Prisma.UserEducationsUncheckedCreateNestedManyWithoutUsersInput
}

export type UsersCreateOrConnectWithoutUser_skillsInput = {
  where: Prisma.UsersWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersCreateWithoutUser_skillsInput, Prisma.UsersUncheckedCreateWithoutUser_skillsInput>
}

export type UsersUpsertWithoutUser_skillsInput = {
  update: Prisma.XOR<Prisma.UsersUpdateWithoutUser_skillsInput, Prisma.UsersUncheckedUpdateWithoutUser_skillsInput>
  create: Prisma.XOR<Prisma.UsersCreateWithoutUser_skillsInput, Prisma.UsersUncheckedCreateWithoutUser_skillsInput>
  where?: Prisma.UsersWhereInput
}

export type UsersUpdateToOneWithWhereWithoutUser_skillsInput = {
  where?: Prisma.UsersWhereInput
  data: Prisma.XOR<Prisma.UsersUpdateWithoutUser_skillsInput, Prisma.UsersUncheckedUpdateWithoutUser_skillsInput>
}

export type UsersUpdateWithoutUser_skillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUpdateManyWithoutUsersNestedInput
  roles?: Prisma.RolesUpdateOneWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutUser_skillsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUncheckedUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUncheckedUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUncheckedUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUncheckedUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersCreateManyRolesInput = {
  id?: string
  full_name: string
  email: string
  password: string
  bio?: string | null
  is_verified?: boolean | null
}

export type UsersUpdateWithoutRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUpdateManyWithoutUsersNestedInput
}

export type UsersUncheckedUpdateWithoutRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  applications?: Prisma.ApplicationsUncheckedUpdateManyWithoutUsersNestedInput
  companies?: Prisma.CompaniesUncheckedUpdateManyWithoutUsersNestedInput
  match_results?: Prisma.MatchResultsUncheckedUpdateManyWithoutUsersNestedInput
  user_badges?: Prisma.UserBadgesUncheckedUpdateManyWithoutUsersNestedInput
  user_educations?: Prisma.UserEducationsUncheckedUpdateManyWithoutUsersNestedInput
  user_skills?: Prisma.UserSkillsUncheckedUpdateManyWithoutUsersNestedInput
}

export type UsersUncheckedUpdateManyWithoutRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  full_name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}


/**
 * Count Type UsersCountOutputType
 */

export type UsersCountOutputType = {
  applications: number
  companies: number
  match_results: number
  user_badges: number
  user_educations: number
  user_skills: number
}

export type UsersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  applications?: boolean | UsersCountOutputTypeCountApplicationsArgs
  companies?: boolean | UsersCountOutputTypeCountCompaniesArgs
  match_results?: boolean | UsersCountOutputTypeCountMatch_resultsArgs
  user_badges?: boolean | UsersCountOutputTypeCountUser_badgesArgs
  user_educations?: boolean | UsersCountOutputTypeCountUser_educationsArgs
  user_skills?: boolean | UsersCountOutputTypeCountUser_skillsArgs
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersCountOutputType
   */
  select?: Prisma.UsersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountApplicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationsWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountCompaniesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompaniesWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountMatch_resultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchResultsWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountUser_badgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBadgesWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountUser_educationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserEducationsWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountUser_skillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserSkillsWhereInput
}


export type UsersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  role_id?: boolean
  full_name?: boolean
  email?: boolean
  password?: boolean
  bio?: boolean
  is_verified?: boolean
  applications?: boolean | Prisma.Users$applicationsArgs<ExtArgs>
  companies?: boolean | Prisma.Users$companiesArgs<ExtArgs>
  match_results?: boolean | Prisma.Users$match_resultsArgs<ExtArgs>
  user_badges?: boolean | Prisma.Users$user_badgesArgs<ExtArgs>
  user_educations?: boolean | Prisma.Users$user_educationsArgs<ExtArgs>
  user_skills?: boolean | Prisma.Users$user_skillsArgs<ExtArgs>
  roles?: boolean | Prisma.Users$rolesArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type UsersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  role_id?: boolean
  full_name?: boolean
  email?: boolean
  password?: boolean
  bio?: boolean
  is_verified?: boolean
  roles?: boolean | Prisma.Users$rolesArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type UsersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  role_id?: boolean
  full_name?: boolean
  email?: boolean
  password?: boolean
  bio?: boolean
  is_verified?: boolean
  roles?: boolean | Prisma.Users$rolesArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type UsersSelectScalar = {
  id?: boolean
  role_id?: boolean
  full_name?: boolean
  email?: boolean
  password?: boolean
  bio?: boolean
  is_verified?: boolean
}

export type UsersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "role_id" | "full_name" | "email" | "password" | "bio" | "is_verified", ExtArgs["result"]["users"]>
export type UsersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  applications?: boolean | Prisma.Users$applicationsArgs<ExtArgs>
  companies?: boolean | Prisma.Users$companiesArgs<ExtArgs>
  match_results?: boolean | Prisma.Users$match_resultsArgs<ExtArgs>
  user_badges?: boolean | Prisma.Users$user_badgesArgs<ExtArgs>
  user_educations?: boolean | Prisma.Users$user_educationsArgs<ExtArgs>
  user_skills?: boolean | Prisma.Users$user_skillsArgs<ExtArgs>
  roles?: boolean | Prisma.Users$rolesArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}
export type UsersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roles?: boolean | Prisma.Users$rolesArgs<ExtArgs>
}
export type UsersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roles?: boolean | Prisma.Users$rolesArgs<ExtArgs>
}

export type $UsersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Users"
  objects: {
    applications: Prisma.$ApplicationsPayload<ExtArgs>[]
    companies: Prisma.$CompaniesPayload<ExtArgs>[]
    match_results: Prisma.$MatchResultsPayload<ExtArgs>[]
    user_badges: Prisma.$UserBadgesPayload<ExtArgs>[]
    user_educations: Prisma.$UserEducationsPayload<ExtArgs>[]
    user_skills: Prisma.$UserSkillsPayload<ExtArgs>[]
    roles: Prisma.$RolesPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    role_id: number | null
    full_name: string
    email: string
    password: string
    bio: string | null
    is_verified: boolean | null
  }, ExtArgs["result"]["users"]>
  composites: {}
}

export type UsersGetPayload<S extends boolean | null | undefined | UsersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UsersPayload, S>

export type UsersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UsersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsersCountAggregateInputType | true
  }

export interface UsersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Users'], meta: { name: 'Users' } }
  /**
   * Find zero or one Users that matches the filter.
   * @param {UsersFindUniqueArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UsersFindUniqueArgs>(args: Prisma.SelectSubset<T, UsersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Users that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UsersFindUniqueOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UsersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UsersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersFindFirstArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UsersFindFirstArgs>(args?: Prisma.SelectSubset<T, UsersFindFirstArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersFindFirstOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UsersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UsersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.users.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.users.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const usersWithIdOnly = await prisma.users.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UsersFindManyArgs>(args?: Prisma.SelectSubset<T, UsersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Users.
   * @param {UsersCreateArgs} args - Arguments to create a Users.
   * @example
   * // Create one Users
   * const Users = await prisma.users.create({
   *   data: {
   *     // ... data to create a Users
   *   }
   * })
   * 
   */
  create<T extends UsersCreateArgs>(args: Prisma.SelectSubset<T, UsersCreateArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UsersCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UsersCreateManyArgs>(args?: Prisma.SelectSubset<T, UsersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UsersCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UsersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UsersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Users.
   * @param {UsersDeleteArgs} args - Arguments to delete one Users.
   * @example
   * // Delete one Users
   * const Users = await prisma.users.delete({
   *   where: {
   *     // ... filter to delete one Users
   *   }
   * })
   * 
   */
  delete<T extends UsersDeleteArgs>(args: Prisma.SelectSubset<T, UsersDeleteArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Users.
   * @param {UsersUpdateArgs} args - Arguments to update one Users.
   * @example
   * // Update one Users
   * const users = await prisma.users.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UsersUpdateArgs>(args: Prisma.SelectSubset<T, UsersUpdateArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UsersDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.users.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UsersDeleteManyArgs>(args?: Prisma.SelectSubset<T, UsersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UsersUpdateManyArgs>(args: Prisma.SelectSubset<T, UsersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UsersUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UsersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UsersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Users.
   * @param {UsersUpsertArgs} args - Arguments to update or create a Users.
   * @example
   * // Update or create a Users
   * const users = await prisma.users.upsert({
   *   create: {
   *     // ... data to create a Users
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Users we want to update
   *   }
   * })
   */
  upsert<T extends UsersUpsertArgs>(args: Prisma.SelectSubset<T, UsersUpsertArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.users.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UsersCountArgs>(
    args?: Prisma.Subset<T, UsersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsersAggregateArgs>(args: Prisma.Subset<T, UsersAggregateArgs>): Prisma.PrismaPromise<GetUsersAggregateType<T>>

  /**
   * Group by Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UsersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UsersGroupByArgs['orderBy'] }
      : { orderBy?: UsersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UsersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Users model
 */
readonly fields: UsersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Users.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UsersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  applications<T extends Prisma.Users$applicationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$applicationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  companies<T extends Prisma.Users$companiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$companiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompaniesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  match_results<T extends Prisma.Users$match_resultsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$match_resultsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchResultsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user_badges<T extends Prisma.Users$user_badgesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$user_badgesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user_educations<T extends Prisma.Users$user_educationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$user_educationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserEducationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user_skills<T extends Prisma.Users$user_skillsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$user_skillsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserSkillsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  roles<T extends Prisma.Users$rolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Users$rolesArgs<ExtArgs>>): Prisma.Prisma__RolesClient<runtime.Types.Result.GetResult<Prisma.$RolesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Users model
 */
export interface UsersFieldRefs {
  readonly id: Prisma.FieldRef<"Users", 'String'>
  readonly role_id: Prisma.FieldRef<"Users", 'Int'>
  readonly full_name: Prisma.FieldRef<"Users", 'String'>
  readonly email: Prisma.FieldRef<"Users", 'String'>
  readonly password: Prisma.FieldRef<"Users", 'String'>
  readonly bio: Prisma.FieldRef<"Users", 'String'>
  readonly is_verified: Prisma.FieldRef<"Users", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Users findUnique
 */
export type UsersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users findUniqueOrThrow
 */
export type UsersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users findFirst
 */
export type UsersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * Users findFirstOrThrow
 */
export type UsersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * Users findMany
 */
export type UsersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * Users create
 */
export type UsersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * The data needed to create a Users.
   */
  data: Prisma.XOR<Prisma.UsersCreateInput, Prisma.UsersUncheckedCreateInput>
}

/**
 * Users createMany
 */
export type UsersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UsersCreateManyInput | Prisma.UsersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Users createManyAndReturn
 */
export type UsersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UsersCreateManyInput | Prisma.UsersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Users update
 */
export type UsersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * The data needed to update a Users.
   */
  data: Prisma.XOR<Prisma.UsersUpdateInput, Prisma.UsersUncheckedUpdateInput>
  /**
   * Choose, which Users to update.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users updateMany
 */
export type UsersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UsersUpdateManyMutationInput, Prisma.UsersUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UsersWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * Users updateManyAndReturn
 */
export type UsersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UsersUpdateManyMutationInput, Prisma.UsersUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UsersWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Users upsert
 */
export type UsersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * The filter to search for the Users to update in case it exists.
   */
  where: Prisma.UsersWhereUniqueInput
  /**
   * In case the Users found by the `where` argument doesn't exist, create a new Users with this data.
   */
  create: Prisma.XOR<Prisma.UsersCreateInput, Prisma.UsersUncheckedCreateInput>
  /**
   * In case the Users was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UsersUpdateInput, Prisma.UsersUncheckedUpdateInput>
}

/**
 * Users delete
 */
export type UsersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  /**
   * Filter which Users to delete.
   */
  where: Prisma.UsersWhereUniqueInput
}

/**
 * Users deleteMany
 */
export type UsersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UsersWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * Users.applications
 */
export type Users$applicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Applications
   */
  select?: Prisma.ApplicationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Applications
   */
  omit?: Prisma.ApplicationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationsInclude<ExtArgs> | null
  where?: Prisma.ApplicationsWhereInput
  orderBy?: Prisma.ApplicationsOrderByWithRelationInput | Prisma.ApplicationsOrderByWithRelationInput[]
  cursor?: Prisma.ApplicationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ApplicationsScalarFieldEnum | Prisma.ApplicationsScalarFieldEnum[]
}

/**
 * Users.companies
 */
export type Users$companiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Companies
   */
  select?: Prisma.CompaniesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Companies
   */
  omit?: Prisma.CompaniesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompaniesInclude<ExtArgs> | null
  where?: Prisma.CompaniesWhereInput
  orderBy?: Prisma.CompaniesOrderByWithRelationInput | Prisma.CompaniesOrderByWithRelationInput[]
  cursor?: Prisma.CompaniesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CompaniesScalarFieldEnum | Prisma.CompaniesScalarFieldEnum[]
}

/**
 * Users.match_results
 */
export type Users$match_resultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchResults
   */
  select?: Prisma.MatchResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchResults
   */
  omit?: Prisma.MatchResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchResultsInclude<ExtArgs> | null
  where?: Prisma.MatchResultsWhereInput
  orderBy?: Prisma.MatchResultsOrderByWithRelationInput | Prisma.MatchResultsOrderByWithRelationInput[]
  cursor?: Prisma.MatchResultsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MatchResultsScalarFieldEnum | Prisma.MatchResultsScalarFieldEnum[]
}

/**
 * Users.user_badges
 */
export type Users$user_badgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  where?: Prisma.UserBadgesWhereInput
  orderBy?: Prisma.UserBadgesOrderByWithRelationInput | Prisma.UserBadgesOrderByWithRelationInput[]
  cursor?: Prisma.UserBadgesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserBadgesScalarFieldEnum | Prisma.UserBadgesScalarFieldEnum[]
}

/**
 * Users.user_educations
 */
export type Users$user_educationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserEducations
   */
  select?: Prisma.UserEducationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserEducations
   */
  omit?: Prisma.UserEducationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserEducationsInclude<ExtArgs> | null
  where?: Prisma.UserEducationsWhereInput
  orderBy?: Prisma.UserEducationsOrderByWithRelationInput | Prisma.UserEducationsOrderByWithRelationInput[]
  cursor?: Prisma.UserEducationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserEducationsScalarFieldEnum | Prisma.UserEducationsScalarFieldEnum[]
}

/**
 * Users.user_skills
 */
export type Users$user_skillsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSkills
   */
  select?: Prisma.UserSkillsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSkills
   */
  omit?: Prisma.UserSkillsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSkillsInclude<ExtArgs> | null
  where?: Prisma.UserSkillsWhereInput
  orderBy?: Prisma.UserSkillsOrderByWithRelationInput | Prisma.UserSkillsOrderByWithRelationInput[]
  cursor?: Prisma.UserSkillsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserSkillsScalarFieldEnum | Prisma.UserSkillsScalarFieldEnum[]
}

/**
 * Users.roles
 */
export type Users$rolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Roles
   */
  select?: Prisma.RolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Roles
   */
  omit?: Prisma.RolesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolesInclude<ExtArgs> | null
  where?: Prisma.RolesWhereInput
}

/**
 * Users without action
 */
export type UsersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
}
