
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserBadges` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserBadges
 * 
 */
export type UserBadgesModel = runtime.Types.Result.DefaultSelection<Prisma.$UserBadgesPayload>

export type AggregateUserBadges = {
  _count: UserBadgesCountAggregateOutputType | null
  _avg: UserBadgesAvgAggregateOutputType | null
  _sum: UserBadgesSumAggregateOutputType | null
  _min: UserBadgesMinAggregateOutputType | null
  _max: UserBadgesMaxAggregateOutputType | null
}

export type UserBadgesAvgAggregateOutputType = {
  id: number | null
  badge_id: number | null
}

export type UserBadgesSumAggregateOutputType = {
  id: number | null
  badge_id: number | null
}

export type UserBadgesMinAggregateOutputType = {
  id: number | null
  user_id: string | null
  badge_id: number | null
}

export type UserBadgesMaxAggregateOutputType = {
  id: number | null
  user_id: string | null
  badge_id: number | null
}

export type UserBadgesCountAggregateOutputType = {
  id: number
  user_id: number
  badge_id: number
  _all: number
}


export type UserBadgesAvgAggregateInputType = {
  id?: true
  badge_id?: true
}

export type UserBadgesSumAggregateInputType = {
  id?: true
  badge_id?: true
}

export type UserBadgesMinAggregateInputType = {
  id?: true
  user_id?: true
  badge_id?: true
}

export type UserBadgesMaxAggregateInputType = {
  id?: true
  user_id?: true
  badge_id?: true
}

export type UserBadgesCountAggregateInputType = {
  id?: true
  user_id?: true
  badge_id?: true
  _all?: true
}

export type UserBadgesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBadges to aggregate.
   */
  where?: Prisma.UserBadgesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBadges to fetch.
   */
  orderBy?: Prisma.UserBadgesOrderByWithRelationInput | Prisma.UserBadgesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserBadgesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBadges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBadges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserBadges
  **/
  _count?: true | UserBadgesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserBadgesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserBadgesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserBadgesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserBadgesMaxAggregateInputType
}

export type GetUserBadgesAggregateType<T extends UserBadgesAggregateArgs> = {
      [P in keyof T & keyof AggregateUserBadges]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserBadges[P]>
    : Prisma.GetScalarType<T[P], AggregateUserBadges[P]>
}




export type UserBadgesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBadgesWhereInput
  orderBy?: Prisma.UserBadgesOrderByWithAggregationInput | Prisma.UserBadgesOrderByWithAggregationInput[]
  by: Prisma.UserBadgesScalarFieldEnum[] | Prisma.UserBadgesScalarFieldEnum
  having?: Prisma.UserBadgesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserBadgesCountAggregateInputType | true
  _avg?: UserBadgesAvgAggregateInputType
  _sum?: UserBadgesSumAggregateInputType
  _min?: UserBadgesMinAggregateInputType
  _max?: UserBadgesMaxAggregateInputType
}

export type UserBadgesGroupByOutputType = {
  id: number
  user_id: string | null
  badge_id: number | null
  _count: UserBadgesCountAggregateOutputType | null
  _avg: UserBadgesAvgAggregateOutputType | null
  _sum: UserBadgesSumAggregateOutputType | null
  _min: UserBadgesMinAggregateOutputType | null
  _max: UserBadgesMaxAggregateOutputType | null
}

type GetUserBadgesGroupByPayload<T extends UserBadgesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserBadgesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserBadgesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserBadgesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserBadgesGroupByOutputType[P]>
      }
    >
  >



export type UserBadgesWhereInput = {
  AND?: Prisma.UserBadgesWhereInput | Prisma.UserBadgesWhereInput[]
  OR?: Prisma.UserBadgesWhereInput[]
  NOT?: Prisma.UserBadgesWhereInput | Prisma.UserBadgesWhereInput[]
  id?: Prisma.IntFilter<"UserBadges"> | number
  user_id?: Prisma.UuidNullableFilter<"UserBadges"> | string | null
  badge_id?: Prisma.IntNullableFilter<"UserBadges"> | number | null
  badges?: Prisma.XOR<Prisma.BadgesNullableScalarRelationFilter, Prisma.BadgesWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.UsersWhereInput> | null
}

export type UserBadgesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  badge_id?: Prisma.SortOrderInput | Prisma.SortOrder
  badges?: Prisma.BadgesOrderByWithRelationInput
  users?: Prisma.UsersOrderByWithRelationInput
}

export type UserBadgesWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.UserBadgesWhereInput | Prisma.UserBadgesWhereInput[]
  OR?: Prisma.UserBadgesWhereInput[]
  NOT?: Prisma.UserBadgesWhereInput | Prisma.UserBadgesWhereInput[]
  user_id?: Prisma.UuidNullableFilter<"UserBadges"> | string | null
  badge_id?: Prisma.IntNullableFilter<"UserBadges"> | number | null
  badges?: Prisma.XOR<Prisma.BadgesNullableScalarRelationFilter, Prisma.BadgesWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.UsersWhereInput> | null
}, "id">

export type UserBadgesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  badge_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserBadgesCountOrderByAggregateInput
  _avg?: Prisma.UserBadgesAvgOrderByAggregateInput
  _max?: Prisma.UserBadgesMaxOrderByAggregateInput
  _min?: Prisma.UserBadgesMinOrderByAggregateInput
  _sum?: Prisma.UserBadgesSumOrderByAggregateInput
}

export type UserBadgesScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserBadgesScalarWhereWithAggregatesInput | Prisma.UserBadgesScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserBadgesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserBadgesScalarWhereWithAggregatesInput | Prisma.UserBadgesScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"UserBadges"> | number
  user_id?: Prisma.UuidNullableWithAggregatesFilter<"UserBadges"> | string | null
  badge_id?: Prisma.IntNullableWithAggregatesFilter<"UserBadges"> | number | null
}

export type UserBadgesCreateInput = {
  badges?: Prisma.BadgesCreateNestedOneWithoutUser_badgesInput
  users?: Prisma.UsersCreateNestedOneWithoutUser_badgesInput
}

export type UserBadgesUncheckedCreateInput = {
  id?: number
  user_id?: string | null
  badge_id?: number | null
}

export type UserBadgesUpdateInput = {
  badges?: Prisma.BadgesUpdateOneWithoutUser_badgesNestedInput
  users?: Prisma.UsersUpdateOneWithoutUser_badgesNestedInput
}

export type UserBadgesUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  badge_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type UserBadgesCreateManyInput = {
  id?: number
  user_id?: string | null
  badge_id?: number | null
}

export type UserBadgesUpdateManyMutationInput = {

}

export type UserBadgesUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  badge_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type UserBadgesListRelationFilter = {
  every?: Prisma.UserBadgesWhereInput
  some?: Prisma.UserBadgesWhereInput
  none?: Prisma.UserBadgesWhereInput
}

export type UserBadgesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserBadgesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  badge_id?: Prisma.SortOrder
}

export type UserBadgesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  badge_id?: Prisma.SortOrder
}

export type UserBadgesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  badge_id?: Prisma.SortOrder
}

export type UserBadgesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  badge_id?: Prisma.SortOrder
}

export type UserBadgesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  badge_id?: Prisma.SortOrder
}

export type UserBadgesCreateNestedManyWithoutBadgesInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutBadgesInput, Prisma.UserBadgesUncheckedCreateWithoutBadgesInput> | Prisma.UserBadgesCreateWithoutBadgesInput[] | Prisma.UserBadgesUncheckedCreateWithoutBadgesInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutBadgesInput | Prisma.UserBadgesCreateOrConnectWithoutBadgesInput[]
  createMany?: Prisma.UserBadgesCreateManyBadgesInputEnvelope
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
}

export type UserBadgesUncheckedCreateNestedManyWithoutBadgesInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutBadgesInput, Prisma.UserBadgesUncheckedCreateWithoutBadgesInput> | Prisma.UserBadgesCreateWithoutBadgesInput[] | Prisma.UserBadgesUncheckedCreateWithoutBadgesInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutBadgesInput | Prisma.UserBadgesCreateOrConnectWithoutBadgesInput[]
  createMany?: Prisma.UserBadgesCreateManyBadgesInputEnvelope
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
}

export type UserBadgesUpdateManyWithoutBadgesNestedInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutBadgesInput, Prisma.UserBadgesUncheckedCreateWithoutBadgesInput> | Prisma.UserBadgesCreateWithoutBadgesInput[] | Prisma.UserBadgesUncheckedCreateWithoutBadgesInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutBadgesInput | Prisma.UserBadgesCreateOrConnectWithoutBadgesInput[]
  upsert?: Prisma.UserBadgesUpsertWithWhereUniqueWithoutBadgesInput | Prisma.UserBadgesUpsertWithWhereUniqueWithoutBadgesInput[]
  createMany?: Prisma.UserBadgesCreateManyBadgesInputEnvelope
  set?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  disconnect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  delete?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  update?: Prisma.UserBadgesUpdateWithWhereUniqueWithoutBadgesInput | Prisma.UserBadgesUpdateWithWhereUniqueWithoutBadgesInput[]
  updateMany?: Prisma.UserBadgesUpdateManyWithWhereWithoutBadgesInput | Prisma.UserBadgesUpdateManyWithWhereWithoutBadgesInput[]
  deleteMany?: Prisma.UserBadgesScalarWhereInput | Prisma.UserBadgesScalarWhereInput[]
}

export type UserBadgesUncheckedUpdateManyWithoutBadgesNestedInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutBadgesInput, Prisma.UserBadgesUncheckedCreateWithoutBadgesInput> | Prisma.UserBadgesCreateWithoutBadgesInput[] | Prisma.UserBadgesUncheckedCreateWithoutBadgesInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutBadgesInput | Prisma.UserBadgesCreateOrConnectWithoutBadgesInput[]
  upsert?: Prisma.UserBadgesUpsertWithWhereUniqueWithoutBadgesInput | Prisma.UserBadgesUpsertWithWhereUniqueWithoutBadgesInput[]
  createMany?: Prisma.UserBadgesCreateManyBadgesInputEnvelope
  set?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  disconnect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  delete?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  update?: Prisma.UserBadgesUpdateWithWhereUniqueWithoutBadgesInput | Prisma.UserBadgesUpdateWithWhereUniqueWithoutBadgesInput[]
  updateMany?: Prisma.UserBadgesUpdateManyWithWhereWithoutBadgesInput | Prisma.UserBadgesUpdateManyWithWhereWithoutBadgesInput[]
  deleteMany?: Prisma.UserBadgesScalarWhereInput | Prisma.UserBadgesScalarWhereInput[]
}

export type UserBadgesCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutUsersInput, Prisma.UserBadgesUncheckedCreateWithoutUsersInput> | Prisma.UserBadgesCreateWithoutUsersInput[] | Prisma.UserBadgesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutUsersInput | Prisma.UserBadgesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.UserBadgesCreateManyUsersInputEnvelope
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
}

export type UserBadgesUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutUsersInput, Prisma.UserBadgesUncheckedCreateWithoutUsersInput> | Prisma.UserBadgesCreateWithoutUsersInput[] | Prisma.UserBadgesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutUsersInput | Prisma.UserBadgesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.UserBadgesCreateManyUsersInputEnvelope
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
}

export type UserBadgesUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutUsersInput, Prisma.UserBadgesUncheckedCreateWithoutUsersInput> | Prisma.UserBadgesCreateWithoutUsersInput[] | Prisma.UserBadgesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutUsersInput | Prisma.UserBadgesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.UserBadgesUpsertWithWhereUniqueWithoutUsersInput | Prisma.UserBadgesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.UserBadgesCreateManyUsersInputEnvelope
  set?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  disconnect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  delete?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  update?: Prisma.UserBadgesUpdateWithWhereUniqueWithoutUsersInput | Prisma.UserBadgesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.UserBadgesUpdateManyWithWhereWithoutUsersInput | Prisma.UserBadgesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.UserBadgesScalarWhereInput | Prisma.UserBadgesScalarWhereInput[]
}

export type UserBadgesUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.UserBadgesCreateWithoutUsersInput, Prisma.UserBadgesUncheckedCreateWithoutUsersInput> | Prisma.UserBadgesCreateWithoutUsersInput[] | Prisma.UserBadgesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.UserBadgesCreateOrConnectWithoutUsersInput | Prisma.UserBadgesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.UserBadgesUpsertWithWhereUniqueWithoutUsersInput | Prisma.UserBadgesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.UserBadgesCreateManyUsersInputEnvelope
  set?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  disconnect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  delete?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  connect?: Prisma.UserBadgesWhereUniqueInput | Prisma.UserBadgesWhereUniqueInput[]
  update?: Prisma.UserBadgesUpdateWithWhereUniqueWithoutUsersInput | Prisma.UserBadgesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.UserBadgesUpdateManyWithWhereWithoutUsersInput | Prisma.UserBadgesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.UserBadgesScalarWhereInput | Prisma.UserBadgesScalarWhereInput[]
}

export type UserBadgesCreateWithoutBadgesInput = {
  users?: Prisma.UsersCreateNestedOneWithoutUser_badgesInput
}

export type UserBadgesUncheckedCreateWithoutBadgesInput = {
  id?: number
  user_id?: string | null
}

export type UserBadgesCreateOrConnectWithoutBadgesInput = {
  where: Prisma.UserBadgesWhereUniqueInput
  create: Prisma.XOR<Prisma.UserBadgesCreateWithoutBadgesInput, Prisma.UserBadgesUncheckedCreateWithoutBadgesInput>
}

export type UserBadgesCreateManyBadgesInputEnvelope = {
  data: Prisma.UserBadgesCreateManyBadgesInput | Prisma.UserBadgesCreateManyBadgesInput[]
  skipDuplicates?: boolean
}

export type UserBadgesUpsertWithWhereUniqueWithoutBadgesInput = {
  where: Prisma.UserBadgesWhereUniqueInput
  update: Prisma.XOR<Prisma.UserBadgesUpdateWithoutBadgesInput, Prisma.UserBadgesUncheckedUpdateWithoutBadgesInput>
  create: Prisma.XOR<Prisma.UserBadgesCreateWithoutBadgesInput, Prisma.UserBadgesUncheckedCreateWithoutBadgesInput>
}

export type UserBadgesUpdateWithWhereUniqueWithoutBadgesInput = {
  where: Prisma.UserBadgesWhereUniqueInput
  data: Prisma.XOR<Prisma.UserBadgesUpdateWithoutBadgesInput, Prisma.UserBadgesUncheckedUpdateWithoutBadgesInput>
}

export type UserBadgesUpdateManyWithWhereWithoutBadgesInput = {
  where: Prisma.UserBadgesScalarWhereInput
  data: Prisma.XOR<Prisma.UserBadgesUpdateManyMutationInput, Prisma.UserBadgesUncheckedUpdateManyWithoutBadgesInput>
}

export type UserBadgesScalarWhereInput = {
  AND?: Prisma.UserBadgesScalarWhereInput | Prisma.UserBadgesScalarWhereInput[]
  OR?: Prisma.UserBadgesScalarWhereInput[]
  NOT?: Prisma.UserBadgesScalarWhereInput | Prisma.UserBadgesScalarWhereInput[]
  id?: Prisma.IntFilter<"UserBadges"> | number
  user_id?: Prisma.UuidNullableFilter<"UserBadges"> | string | null
  badge_id?: Prisma.IntNullableFilter<"UserBadges"> | number | null
}

export type UserBadgesCreateWithoutUsersInput = {
  badges?: Prisma.BadgesCreateNestedOneWithoutUser_badgesInput
}

export type UserBadgesUncheckedCreateWithoutUsersInput = {
  id?: number
  badge_id?: number | null
}

export type UserBadgesCreateOrConnectWithoutUsersInput = {
  where: Prisma.UserBadgesWhereUniqueInput
  create: Prisma.XOR<Prisma.UserBadgesCreateWithoutUsersInput, Prisma.UserBadgesUncheckedCreateWithoutUsersInput>
}

export type UserBadgesCreateManyUsersInputEnvelope = {
  data: Prisma.UserBadgesCreateManyUsersInput | Prisma.UserBadgesCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type UserBadgesUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.UserBadgesWhereUniqueInput
  update: Prisma.XOR<Prisma.UserBadgesUpdateWithoutUsersInput, Prisma.UserBadgesUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.UserBadgesCreateWithoutUsersInput, Prisma.UserBadgesUncheckedCreateWithoutUsersInput>
}

export type UserBadgesUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.UserBadgesWhereUniqueInput
  data: Prisma.XOR<Prisma.UserBadgesUpdateWithoutUsersInput, Prisma.UserBadgesUncheckedUpdateWithoutUsersInput>
}

export type UserBadgesUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.UserBadgesScalarWhereInput
  data: Prisma.XOR<Prisma.UserBadgesUpdateManyMutationInput, Prisma.UserBadgesUncheckedUpdateManyWithoutUsersInput>
}

export type UserBadgesCreateManyBadgesInput = {
  id?: number
  user_id?: string | null
}

export type UserBadgesUpdateWithoutBadgesInput = {
  users?: Prisma.UsersUpdateOneWithoutUser_badgesNestedInput
}

export type UserBadgesUncheckedUpdateWithoutBadgesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UserBadgesUncheckedUpdateManyWithoutBadgesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UserBadgesCreateManyUsersInput = {
  id?: number
  badge_id?: number | null
}

export type UserBadgesUpdateWithoutUsersInput = {
  badges?: Prisma.BadgesUpdateOneWithoutUser_badgesNestedInput
}

export type UserBadgesUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  badge_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type UserBadgesUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  badge_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type UserBadgesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  badge_id?: boolean
  badges?: boolean | Prisma.UserBadges$badgesArgs<ExtArgs>
  users?: boolean | Prisma.UserBadges$usersArgs<ExtArgs>
}, ExtArgs["result"]["userBadges"]>

export type UserBadgesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  badge_id?: boolean
  badges?: boolean | Prisma.UserBadges$badgesArgs<ExtArgs>
  users?: boolean | Prisma.UserBadges$usersArgs<ExtArgs>
}, ExtArgs["result"]["userBadges"]>

export type UserBadgesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  badge_id?: boolean
  badges?: boolean | Prisma.UserBadges$badgesArgs<ExtArgs>
  users?: boolean | Prisma.UserBadges$usersArgs<ExtArgs>
}, ExtArgs["result"]["userBadges"]>

export type UserBadgesSelectScalar = {
  id?: boolean
  user_id?: boolean
  badge_id?: boolean
}

export type UserBadgesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "badge_id", ExtArgs["result"]["userBadges"]>
export type UserBadgesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  badges?: boolean | Prisma.UserBadges$badgesArgs<ExtArgs>
  users?: boolean | Prisma.UserBadges$usersArgs<ExtArgs>
}
export type UserBadgesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  badges?: boolean | Prisma.UserBadges$badgesArgs<ExtArgs>
  users?: boolean | Prisma.UserBadges$usersArgs<ExtArgs>
}
export type UserBadgesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  badges?: boolean | Prisma.UserBadges$badgesArgs<ExtArgs>
  users?: boolean | Prisma.UserBadges$usersArgs<ExtArgs>
}

export type $UserBadgesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserBadges"
  objects: {
    badges: Prisma.$BadgesPayload<ExtArgs> | null
    users: Prisma.$UsersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: string | null
    badge_id: number | null
  }, ExtArgs["result"]["userBadges"]>
  composites: {}
}

export type UserBadgesGetPayload<S extends boolean | null | undefined | UserBadgesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload, S>

export type UserBadgesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserBadgesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserBadgesCountAggregateInputType | true
  }

export interface UserBadgesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserBadges'], meta: { name: 'UserBadges' } }
  /**
   * Find zero or one UserBadges that matches the filter.
   * @param {UserBadgesFindUniqueArgs} args - Arguments to find a UserBadges
   * @example
   * // Get one UserBadges
   * const userBadges = await prisma.userBadges.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserBadgesFindUniqueArgs>(args: Prisma.SelectSubset<T, UserBadgesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserBadges that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserBadgesFindUniqueOrThrowArgs} args - Arguments to find a UserBadges
   * @example
   * // Get one UserBadges
   * const userBadges = await prisma.userBadges.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserBadgesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserBadgesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBadges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBadgesFindFirstArgs} args - Arguments to find a UserBadges
   * @example
   * // Get one UserBadges
   * const userBadges = await prisma.userBadges.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserBadgesFindFirstArgs>(args?: Prisma.SelectSubset<T, UserBadgesFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBadges that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBadgesFindFirstOrThrowArgs} args - Arguments to find a UserBadges
   * @example
   * // Get one UserBadges
   * const userBadges = await prisma.userBadges.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserBadgesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserBadgesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserBadges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBadgesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserBadges
   * const userBadges = await prisma.userBadges.findMany()
   * 
   * // Get first 10 UserBadges
   * const userBadges = await prisma.userBadges.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userBadgesWithIdOnly = await prisma.userBadges.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserBadgesFindManyArgs>(args?: Prisma.SelectSubset<T, UserBadgesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserBadges.
   * @param {UserBadgesCreateArgs} args - Arguments to create a UserBadges.
   * @example
   * // Create one UserBadges
   * const UserBadges = await prisma.userBadges.create({
   *   data: {
   *     // ... data to create a UserBadges
   *   }
   * })
   * 
   */
  create<T extends UserBadgesCreateArgs>(args: Prisma.SelectSubset<T, UserBadgesCreateArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserBadges.
   * @param {UserBadgesCreateManyArgs} args - Arguments to create many UserBadges.
   * @example
   * // Create many UserBadges
   * const userBadges = await prisma.userBadges.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserBadgesCreateManyArgs>(args?: Prisma.SelectSubset<T, UserBadgesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserBadges and returns the data saved in the database.
   * @param {UserBadgesCreateManyAndReturnArgs} args - Arguments to create many UserBadges.
   * @example
   * // Create many UserBadges
   * const userBadges = await prisma.userBadges.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserBadges and only return the `id`
   * const userBadgesWithIdOnly = await prisma.userBadges.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserBadgesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserBadgesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserBadges.
   * @param {UserBadgesDeleteArgs} args - Arguments to delete one UserBadges.
   * @example
   * // Delete one UserBadges
   * const UserBadges = await prisma.userBadges.delete({
   *   where: {
   *     // ... filter to delete one UserBadges
   *   }
   * })
   * 
   */
  delete<T extends UserBadgesDeleteArgs>(args: Prisma.SelectSubset<T, UserBadgesDeleteArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserBadges.
   * @param {UserBadgesUpdateArgs} args - Arguments to update one UserBadges.
   * @example
   * // Update one UserBadges
   * const userBadges = await prisma.userBadges.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserBadgesUpdateArgs>(args: Prisma.SelectSubset<T, UserBadgesUpdateArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserBadges.
   * @param {UserBadgesDeleteManyArgs} args - Arguments to filter UserBadges to delete.
   * @example
   * // Delete a few UserBadges
   * const { count } = await prisma.userBadges.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserBadgesDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserBadgesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBadges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBadgesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserBadges
   * const userBadges = await prisma.userBadges.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserBadgesUpdateManyArgs>(args: Prisma.SelectSubset<T, UserBadgesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBadges and returns the data updated in the database.
   * @param {UserBadgesUpdateManyAndReturnArgs} args - Arguments to update many UserBadges.
   * @example
   * // Update many UserBadges
   * const userBadges = await prisma.userBadges.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserBadges and only return the `id`
   * const userBadgesWithIdOnly = await prisma.userBadges.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserBadgesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserBadgesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserBadges.
   * @param {UserBadgesUpsertArgs} args - Arguments to update or create a UserBadges.
   * @example
   * // Update or create a UserBadges
   * const userBadges = await prisma.userBadges.upsert({
   *   create: {
   *     // ... data to create a UserBadges
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserBadges we want to update
   *   }
   * })
   */
  upsert<T extends UserBadgesUpsertArgs>(args: Prisma.SelectSubset<T, UserBadgesUpsertArgs<ExtArgs>>): Prisma.Prisma__UserBadgesClient<runtime.Types.Result.GetResult<Prisma.$UserBadgesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserBadges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBadgesCountArgs} args - Arguments to filter UserBadges to count.
   * @example
   * // Count the number of UserBadges
   * const count = await prisma.userBadges.count({
   *   where: {
   *     // ... the filter for the UserBadges we want to count
   *   }
   * })
  **/
  count<T extends UserBadgesCountArgs>(
    args?: Prisma.Subset<T, UserBadgesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserBadgesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserBadges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBadgesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserBadgesAggregateArgs>(args: Prisma.Subset<T, UserBadgesAggregateArgs>): Prisma.PrismaPromise<GetUserBadgesAggregateType<T>>

  /**
   * Group by UserBadges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBadgesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserBadgesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserBadgesGroupByArgs['orderBy'] }
      : { orderBy?: UserBadgesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserBadgesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserBadgesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserBadges model
 */
readonly fields: UserBadgesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserBadges.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserBadgesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  badges<T extends Prisma.UserBadges$badgesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserBadges$badgesArgs<ExtArgs>>): Prisma.Prisma__BadgesClient<runtime.Types.Result.GetResult<Prisma.$BadgesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.UserBadges$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserBadges$usersArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserBadges model
 */
export interface UserBadgesFieldRefs {
  readonly id: Prisma.FieldRef<"UserBadges", 'Int'>
  readonly user_id: Prisma.FieldRef<"UserBadges", 'String'>
  readonly badge_id: Prisma.FieldRef<"UserBadges", 'Int'>
}
    

// Custom InputTypes
/**
 * UserBadges findUnique
 */
export type UserBadgesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * Filter, which UserBadges to fetch.
   */
  where: Prisma.UserBadgesWhereUniqueInput
}

/**
 * UserBadges findUniqueOrThrow
 */
export type UserBadgesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * Filter, which UserBadges to fetch.
   */
  where: Prisma.UserBadgesWhereUniqueInput
}

/**
 * UserBadges findFirst
 */
export type UserBadgesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * Filter, which UserBadges to fetch.
   */
  where?: Prisma.UserBadgesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBadges to fetch.
   */
  orderBy?: Prisma.UserBadgesOrderByWithRelationInput | Prisma.UserBadgesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBadges.
   */
  cursor?: Prisma.UserBadgesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBadges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBadges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBadges.
   */
  distinct?: Prisma.UserBadgesScalarFieldEnum | Prisma.UserBadgesScalarFieldEnum[]
}

/**
 * UserBadges findFirstOrThrow
 */
export type UserBadgesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * Filter, which UserBadges to fetch.
   */
  where?: Prisma.UserBadgesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBadges to fetch.
   */
  orderBy?: Prisma.UserBadgesOrderByWithRelationInput | Prisma.UserBadgesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBadges.
   */
  cursor?: Prisma.UserBadgesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBadges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBadges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBadges.
   */
  distinct?: Prisma.UserBadgesScalarFieldEnum | Prisma.UserBadgesScalarFieldEnum[]
}

/**
 * UserBadges findMany
 */
export type UserBadgesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * Filter, which UserBadges to fetch.
   */
  where?: Prisma.UserBadgesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBadges to fetch.
   */
  orderBy?: Prisma.UserBadgesOrderByWithRelationInput | Prisma.UserBadgesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserBadges.
   */
  cursor?: Prisma.UserBadgesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBadges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBadges.
   */
  skip?: number
  distinct?: Prisma.UserBadgesScalarFieldEnum | Prisma.UserBadgesScalarFieldEnum[]
}

/**
 * UserBadges create
 */
export type UserBadgesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * The data needed to create a UserBadges.
   */
  data?: Prisma.XOR<Prisma.UserBadgesCreateInput, Prisma.UserBadgesUncheckedCreateInput>
}

/**
 * UserBadges createMany
 */
export type UserBadgesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserBadges.
   */
  data: Prisma.UserBadgesCreateManyInput | Prisma.UserBadgesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserBadges createManyAndReturn
 */
export type UserBadgesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * The data used to create many UserBadges.
   */
  data: Prisma.UserBadgesCreateManyInput | Prisma.UserBadgesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserBadges update
 */
export type UserBadgesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * The data needed to update a UserBadges.
   */
  data: Prisma.XOR<Prisma.UserBadgesUpdateInput, Prisma.UserBadgesUncheckedUpdateInput>
  /**
   * Choose, which UserBadges to update.
   */
  where: Prisma.UserBadgesWhereUniqueInput
}

/**
 * UserBadges updateMany
 */
export type UserBadgesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserBadges.
   */
  data: Prisma.XOR<Prisma.UserBadgesUpdateManyMutationInput, Prisma.UserBadgesUncheckedUpdateManyInput>
  /**
   * Filter which UserBadges to update
   */
  where?: Prisma.UserBadgesWhereInput
  /**
   * Limit how many UserBadges to update.
   */
  limit?: number
}

/**
 * UserBadges updateManyAndReturn
 */
export type UserBadgesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * The data used to update UserBadges.
   */
  data: Prisma.XOR<Prisma.UserBadgesUpdateManyMutationInput, Prisma.UserBadgesUncheckedUpdateManyInput>
  /**
   * Filter which UserBadges to update
   */
  where?: Prisma.UserBadgesWhereInput
  /**
   * Limit how many UserBadges to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserBadges upsert
 */
export type UserBadgesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * The filter to search for the UserBadges to update in case it exists.
   */
  where: Prisma.UserBadgesWhereUniqueInput
  /**
   * In case the UserBadges found by the `where` argument doesn't exist, create a new UserBadges with this data.
   */
  create: Prisma.XOR<Prisma.UserBadgesCreateInput, Prisma.UserBadgesUncheckedCreateInput>
  /**
   * In case the UserBadges was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserBadgesUpdateInput, Prisma.UserBadgesUncheckedUpdateInput>
}

/**
 * UserBadges delete
 */
export type UserBadgesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
  /**
   * Filter which UserBadges to delete.
   */
  where: Prisma.UserBadgesWhereUniqueInput
}

/**
 * UserBadges deleteMany
 */
export type UserBadgesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBadges to delete
   */
  where?: Prisma.UserBadgesWhereInput
  /**
   * Limit how many UserBadges to delete.
   */
  limit?: number
}

/**
 * UserBadges.badges
 */
export type UserBadges$badgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Badges
   */
  select?: Prisma.BadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Badges
   */
  omit?: Prisma.BadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BadgesInclude<ExtArgs> | null
  where?: Prisma.BadgesWhereInput
}

/**
 * UserBadges.users
 */
export type UserBadges$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  where?: Prisma.UsersWhereInput
}

/**
 * UserBadges without action
 */
export type UserBadgesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBadges
   */
  select?: Prisma.UserBadgesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBadges
   */
  omit?: Prisma.UserBadgesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBadgesInclude<ExtArgs> | null
}
