
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
export const prismaVersion: PrismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Applications: 'Applications',
  Badges: 'Badges',
  Companies: 'Companies',
  JobSkills: 'JobSkills',
  Jobs: 'Jobs',
  MatchResults: 'MatchResults',
  Roles: 'Roles',
  Skills: 'Skills',
  UserBadges: 'UserBadges',
  UserEducations: 'UserEducations',
  UserSkills: 'UserSkills',
  Users: 'Users'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "applications" | "badges" | "companies" | "jobSkills" | "jobs" | "matchResults" | "roles" | "skills" | "userBadges" | "userEducations" | "userSkills" | "users"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Applications: {
      payload: Prisma.$ApplicationsPayload<ExtArgs>
      fields: Prisma.ApplicationsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ApplicationsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ApplicationsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>
        }
        findFirst: {
          args: Prisma.ApplicationsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ApplicationsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>
        }
        findMany: {
          args: Prisma.ApplicationsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>[]
        }
        create: {
          args: Prisma.ApplicationsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>
        }
        createMany: {
          args: Prisma.ApplicationsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ApplicationsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>[]
        }
        delete: {
          args: Prisma.ApplicationsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>
        }
        update: {
          args: Prisma.ApplicationsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>
        }
        deleteMany: {
          args: Prisma.ApplicationsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ApplicationsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ApplicationsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>[]
        }
        upsert: {
          args: Prisma.ApplicationsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationsPayload>
        }
        aggregate: {
          args: Prisma.ApplicationsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateApplications>
        }
        groupBy: {
          args: Prisma.ApplicationsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApplicationsGroupByOutputType>[]
        }
        count: {
          args: Prisma.ApplicationsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApplicationsCountAggregateOutputType> | number
        }
      }
    }
    Badges: {
      payload: Prisma.$BadgesPayload<ExtArgs>
      fields: Prisma.BadgesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BadgesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BadgesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>
        }
        findFirst: {
          args: Prisma.BadgesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BadgesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>
        }
        findMany: {
          args: Prisma.BadgesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>[]
        }
        create: {
          args: Prisma.BadgesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>
        }
        createMany: {
          args: Prisma.BadgesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BadgesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>[]
        }
        delete: {
          args: Prisma.BadgesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>
        }
        update: {
          args: Prisma.BadgesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>
        }
        deleteMany: {
          args: Prisma.BadgesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BadgesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BadgesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>[]
        }
        upsert: {
          args: Prisma.BadgesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BadgesPayload>
        }
        aggregate: {
          args: Prisma.BadgesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBadges>
        }
        groupBy: {
          args: Prisma.BadgesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BadgesGroupByOutputType>[]
        }
        count: {
          args: Prisma.BadgesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BadgesCountAggregateOutputType> | number
        }
      }
    }
    Companies: {
      payload: Prisma.$CompaniesPayload<ExtArgs>
      fields: Prisma.CompaniesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CompaniesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CompaniesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        findFirst: {
          args: Prisma.CompaniesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CompaniesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        findMany: {
          args: Prisma.CompaniesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>[]
        }
        create: {
          args: Prisma.CompaniesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        createMany: {
          args: Prisma.CompaniesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CompaniesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>[]
        }
        delete: {
          args: Prisma.CompaniesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        update: {
          args: Prisma.CompaniesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        deleteMany: {
          args: Prisma.CompaniesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CompaniesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CompaniesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>[]
        }
        upsert: {
          args: Prisma.CompaniesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        aggregate: {
          args: Prisma.CompaniesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCompanies>
        }
        groupBy: {
          args: Prisma.CompaniesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompaniesGroupByOutputType>[]
        }
        count: {
          args: Prisma.CompaniesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompaniesCountAggregateOutputType> | number
        }
      }
    }
    JobSkills: {
      payload: Prisma.$JobSkillsPayload<ExtArgs>
      fields: Prisma.JobSkillsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.JobSkillsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.JobSkillsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>
        }
        findFirst: {
          args: Prisma.JobSkillsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.JobSkillsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>
        }
        findMany: {
          args: Prisma.JobSkillsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>[]
        }
        create: {
          args: Prisma.JobSkillsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>
        }
        createMany: {
          args: Prisma.JobSkillsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.JobSkillsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>[]
        }
        delete: {
          args: Prisma.JobSkillsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>
        }
        update: {
          args: Prisma.JobSkillsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>
        }
        deleteMany: {
          args: Prisma.JobSkillsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.JobSkillsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.JobSkillsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>[]
        }
        upsert: {
          args: Prisma.JobSkillsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobSkillsPayload>
        }
        aggregate: {
          args: Prisma.JobSkillsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateJobSkills>
        }
        groupBy: {
          args: Prisma.JobSkillsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.JobSkillsGroupByOutputType>[]
        }
        count: {
          args: Prisma.JobSkillsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.JobSkillsCountAggregateOutputType> | number
        }
      }
    }
    Jobs: {
      payload: Prisma.$JobsPayload<ExtArgs>
      fields: Prisma.JobsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.JobsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.JobsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>
        }
        findFirst: {
          args: Prisma.JobsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.JobsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>
        }
        findMany: {
          args: Prisma.JobsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>[]
        }
        create: {
          args: Prisma.JobsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>
        }
        createMany: {
          args: Prisma.JobsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.JobsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>[]
        }
        delete: {
          args: Prisma.JobsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>
        }
        update: {
          args: Prisma.JobsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>
        }
        deleteMany: {
          args: Prisma.JobsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.JobsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.JobsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>[]
        }
        upsert: {
          args: Prisma.JobsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$JobsPayload>
        }
        aggregate: {
          args: Prisma.JobsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateJobs>
        }
        groupBy: {
          args: Prisma.JobsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.JobsGroupByOutputType>[]
        }
        count: {
          args: Prisma.JobsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.JobsCountAggregateOutputType> | number
        }
      }
    }
    MatchResults: {
      payload: Prisma.$MatchResultsPayload<ExtArgs>
      fields: Prisma.MatchResultsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MatchResultsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MatchResultsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>
        }
        findFirst: {
          args: Prisma.MatchResultsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MatchResultsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>
        }
        findMany: {
          args: Prisma.MatchResultsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>[]
        }
        create: {
          args: Prisma.MatchResultsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>
        }
        createMany: {
          args: Prisma.MatchResultsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MatchResultsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>[]
        }
        delete: {
          args: Prisma.MatchResultsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>
        }
        update: {
          args: Prisma.MatchResultsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>
        }
        deleteMany: {
          args: Prisma.MatchResultsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MatchResultsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MatchResultsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>[]
        }
        upsert: {
          args: Prisma.MatchResultsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MatchResultsPayload>
        }
        aggregate: {
          args: Prisma.MatchResultsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMatchResults>
        }
        groupBy: {
          args: Prisma.MatchResultsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MatchResultsGroupByOutputType>[]
        }
        count: {
          args: Prisma.MatchResultsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MatchResultsCountAggregateOutputType> | number
        }
      }
    }
    Roles: {
      payload: Prisma.$RolesPayload<ExtArgs>
      fields: Prisma.RolesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RolesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RolesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        findFirst: {
          args: Prisma.RolesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RolesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        findMany: {
          args: Prisma.RolesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>[]
        }
        create: {
          args: Prisma.RolesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        createMany: {
          args: Prisma.RolesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RolesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>[]
        }
        delete: {
          args: Prisma.RolesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        update: {
          args: Prisma.RolesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        deleteMany: {
          args: Prisma.RolesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RolesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RolesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>[]
        }
        upsert: {
          args: Prisma.RolesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        aggregate: {
          args: Prisma.RolesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRoles>
        }
        groupBy: {
          args: Prisma.RolesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RolesGroupByOutputType>[]
        }
        count: {
          args: Prisma.RolesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RolesCountAggregateOutputType> | number
        }
      }
    }
    Skills: {
      payload: Prisma.$SkillsPayload<ExtArgs>
      fields: Prisma.SkillsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SkillsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SkillsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>
        }
        findFirst: {
          args: Prisma.SkillsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SkillsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>
        }
        findMany: {
          args: Prisma.SkillsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>[]
        }
        create: {
          args: Prisma.SkillsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>
        }
        createMany: {
          args: Prisma.SkillsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SkillsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>[]
        }
        delete: {
          args: Prisma.SkillsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>
        }
        update: {
          args: Prisma.SkillsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>
        }
        deleteMany: {
          args: Prisma.SkillsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SkillsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SkillsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>[]
        }
        upsert: {
          args: Prisma.SkillsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SkillsPayload>
        }
        aggregate: {
          args: Prisma.SkillsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSkills>
        }
        groupBy: {
          args: Prisma.SkillsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SkillsGroupByOutputType>[]
        }
        count: {
          args: Prisma.SkillsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SkillsCountAggregateOutputType> | number
        }
      }
    }
    UserBadges: {
      payload: Prisma.$UserBadgesPayload<ExtArgs>
      fields: Prisma.UserBadgesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserBadgesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserBadgesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>
        }
        findFirst: {
          args: Prisma.UserBadgesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserBadgesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>
        }
        findMany: {
          args: Prisma.UserBadgesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>[]
        }
        create: {
          args: Prisma.UserBadgesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>
        }
        createMany: {
          args: Prisma.UserBadgesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserBadgesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>[]
        }
        delete: {
          args: Prisma.UserBadgesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>
        }
        update: {
          args: Prisma.UserBadgesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>
        }
        deleteMany: {
          args: Prisma.UserBadgesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserBadgesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserBadgesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>[]
        }
        upsert: {
          args: Prisma.UserBadgesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBadgesPayload>
        }
        aggregate: {
          args: Prisma.UserBadgesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserBadges>
        }
        groupBy: {
          args: Prisma.UserBadgesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserBadgesGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserBadgesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserBadgesCountAggregateOutputType> | number
        }
      }
    }
    UserEducations: {
      payload: Prisma.$UserEducationsPayload<ExtArgs>
      fields: Prisma.UserEducationsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserEducationsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserEducationsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>
        }
        findFirst: {
          args: Prisma.UserEducationsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserEducationsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>
        }
        findMany: {
          args: Prisma.UserEducationsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>[]
        }
        create: {
          args: Prisma.UserEducationsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>
        }
        createMany: {
          args: Prisma.UserEducationsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserEducationsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>[]
        }
        delete: {
          args: Prisma.UserEducationsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>
        }
        update: {
          args: Prisma.UserEducationsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>
        }
        deleteMany: {
          args: Prisma.UserEducationsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserEducationsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserEducationsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>[]
        }
        upsert: {
          args: Prisma.UserEducationsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserEducationsPayload>
        }
        aggregate: {
          args: Prisma.UserEducationsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserEducations>
        }
        groupBy: {
          args: Prisma.UserEducationsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserEducationsGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserEducationsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserEducationsCountAggregateOutputType> | number
        }
      }
    }
    UserSkills: {
      payload: Prisma.$UserSkillsPayload<ExtArgs>
      fields: Prisma.UserSkillsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserSkillsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserSkillsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>
        }
        findFirst: {
          args: Prisma.UserSkillsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserSkillsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>
        }
        findMany: {
          args: Prisma.UserSkillsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>[]
        }
        create: {
          args: Prisma.UserSkillsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>
        }
        createMany: {
          args: Prisma.UserSkillsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserSkillsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>[]
        }
        delete: {
          args: Prisma.UserSkillsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>
        }
        update: {
          args: Prisma.UserSkillsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>
        }
        deleteMany: {
          args: Prisma.UserSkillsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserSkillsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserSkillsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>[]
        }
        upsert: {
          args: Prisma.UserSkillsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSkillsPayload>
        }
        aggregate: {
          args: Prisma.UserSkillsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserSkills>
        }
        groupBy: {
          args: Prisma.UserSkillsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserSkillsGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserSkillsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserSkillsCountAggregateOutputType> | number
        }
      }
    }
    Users: {
      payload: Prisma.$UsersPayload<ExtArgs>
      fields: Prisma.UsersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UsersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UsersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findFirst: {
          args: Prisma.UsersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UsersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findMany: {
          args: Prisma.UsersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        create: {
          args: Prisma.UsersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        createMany: {
          args: Prisma.UsersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UsersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        delete: {
          args: Prisma.UsersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        update: {
          args: Prisma.UsersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        deleteMany: {
          args: Prisma.UsersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UsersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UsersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        upsert: {
          args: Prisma.UsersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        aggregate: {
          args: Prisma.UsersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsers>
        }
        groupBy: {
          args: Prisma.UsersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersGroupByOutputType>[]
        }
        count: {
          args: Prisma.UsersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ApplicationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  job_id: 'job_id',
  status: 'status'
} as const

export type ApplicationsScalarFieldEnum = (typeof ApplicationsScalarFieldEnum)[keyof typeof ApplicationsScalarFieldEnum]


export const BadgesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type BadgesScalarFieldEnum = (typeof BadgesScalarFieldEnum)[keyof typeof BadgesScalarFieldEnum]


export const CompaniesScalarFieldEnum = {
  id: 'id',
  owner_id: 'owner_id',
  company_name: 'company_name',
  description: 'description',
  email: 'email',
  location: 'location',
  website: 'website'
} as const

export type CompaniesScalarFieldEnum = (typeof CompaniesScalarFieldEnum)[keyof typeof CompaniesScalarFieldEnum]


export const JobSkillsScalarFieldEnum = {
  id: 'id',
  job_id: 'job_id',
  skill_id: 'skill_id',
  required_level: 'required_level'
} as const

export type JobSkillsScalarFieldEnum = (typeof JobSkillsScalarFieldEnum)[keyof typeof JobSkillsScalarFieldEnum]


export const JobsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  category: 'category',
  title: 'title',
  description: 'description',
  salary: 'salary',
  is_active: 'is_active'
} as const

export type JobsScalarFieldEnum = (typeof JobsScalarFieldEnum)[keyof typeof JobsScalarFieldEnum]


export const MatchResultsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  job_id: 'job_id',
  match_percentage: 'match_percentage',
  recommendation_type: 'recommendation_type'
} as const

export type MatchResultsScalarFieldEnum = (typeof MatchResultsScalarFieldEnum)[keyof typeof MatchResultsScalarFieldEnum]


export const RolesScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type RolesScalarFieldEnum = (typeof RolesScalarFieldEnum)[keyof typeof RolesScalarFieldEnum]


export const SkillsScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type SkillsScalarFieldEnum = (typeof SkillsScalarFieldEnum)[keyof typeof SkillsScalarFieldEnum]


export const UserBadgesScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  badge_id: 'badge_id'
} as const

export type UserBadgesScalarFieldEnum = (typeof UserBadgesScalarFieldEnum)[keyof typeof UserBadgesScalarFieldEnum]


export const UserEducationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  level: 'level',
  institution_name: 'institution_name',
  graduation_year: 'graduation_year'
} as const

export type UserEducationsScalarFieldEnum = (typeof UserEducationsScalarFieldEnum)[keyof typeof UserEducationsScalarFieldEnum]


export const UserSkillsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  skill_id: 'skill_id',
  level: 'level'
} as const

export type UserSkillsScalarFieldEnum = (typeof UserSkillsScalarFieldEnum)[keyof typeof UserSkillsScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  role_id: 'role_id',
  full_name: 'full_name',
  email: 'email',
  password: 'password',
  bio: 'bio',
  is_verified: 'is_verified'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'ApplicationStatus'
 */
export type EnumApplicationStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ApplicationStatus'>
    


/**
 * Reference to a field of type 'ApplicationStatus[]'
 */
export type ListEnumApplicationStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ApplicationStatus[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  applications?: Prisma.ApplicationsOmit
  badges?: Prisma.BadgesOmit
  companies?: Prisma.CompaniesOmit
  jobSkills?: Prisma.JobSkillsOmit
  jobs?: Prisma.JobsOmit
  matchResults?: Prisma.MatchResultsOmit
  roles?: Prisma.RolesOmit
  skills?: Prisma.SkillsOmit
  userBadges?: Prisma.UserBadgesOmit
  userEducations?: Prisma.UserEducationsOmit
  userSkills?: Prisma.UserSkillsOmit
  users?: Prisma.UsersOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

