
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Applications: 'Applications',
  Badges: 'Badges',
  Companies: 'Companies',
  JobSkills: 'JobSkills',
  Jobs: 'Jobs',
  MatchResults: 'MatchResults',
  Roles: 'Roles',
  Skills: 'Skills',
  UserBadges: 'UserBadges',
  UserEducations: 'UserEducations',
  UserSkills: 'UserSkills',
  Users: 'Users'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ApplicationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  job_id: 'job_id',
  status: 'status'
} as const

export type ApplicationsScalarFieldEnum = (typeof ApplicationsScalarFieldEnum)[keyof typeof ApplicationsScalarFieldEnum]


export const BadgesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type BadgesScalarFieldEnum = (typeof BadgesScalarFieldEnum)[keyof typeof BadgesScalarFieldEnum]


export const CompaniesScalarFieldEnum = {
  id: 'id',
  owner_id: 'owner_id',
  company_name: 'company_name',
  description: 'description',
  email: 'email',
  location: 'location',
  website: 'website'
} as const

export type CompaniesScalarFieldEnum = (typeof CompaniesScalarFieldEnum)[keyof typeof CompaniesScalarFieldEnum]


export const JobSkillsScalarFieldEnum = {
  id: 'id',
  job_id: 'job_id',
  skill_id: 'skill_id',
  required_level: 'required_level'
} as const

export type JobSkillsScalarFieldEnum = (typeof JobSkillsScalarFieldEnum)[keyof typeof JobSkillsScalarFieldEnum]


export const JobsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  category: 'category',
  title: 'title',
  description: 'description',
  salary: 'salary',
  is_active: 'is_active'
} as const

export type JobsScalarFieldEnum = (typeof JobsScalarFieldEnum)[keyof typeof JobsScalarFieldEnum]


export const MatchResultsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  job_id: 'job_id',
  match_percentage: 'match_percentage',
  recommendation_type: 'recommendation_type'
} as const

export type MatchResultsScalarFieldEnum = (typeof MatchResultsScalarFieldEnum)[keyof typeof MatchResultsScalarFieldEnum]


export const RolesScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type RolesScalarFieldEnum = (typeof RolesScalarFieldEnum)[keyof typeof RolesScalarFieldEnum]


export const SkillsScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type SkillsScalarFieldEnum = (typeof SkillsScalarFieldEnum)[keyof typeof SkillsScalarFieldEnum]


export const UserBadgesScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  badge_id: 'badge_id'
} as const

export type UserBadgesScalarFieldEnum = (typeof UserBadgesScalarFieldEnum)[keyof typeof UserBadgesScalarFieldEnum]


export const UserEducationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  level: 'level',
  institution_name: 'institution_name',
  graduation_year: 'graduation_year'
} as const

export type UserEducationsScalarFieldEnum = (typeof UserEducationsScalarFieldEnum)[keyof typeof UserEducationsScalarFieldEnum]


export const UserSkillsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  skill_id: 'skill_id',
  level: 'level'
} as const

export type UserSkillsScalarFieldEnum = (typeof UserSkillsScalarFieldEnum)[keyof typeof UserSkillsScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  role_id: 'role_id',
  full_name: 'full_name',
  email: 'email',
  password: 'password',
  bio: 'bio',
  is_verified: 'is_verified'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

