
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Applications
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type Applications = Prisma.ApplicationsModel
/**
 * Model Badges
 * 
 */
export type Badges = Prisma.BadgesModel
/**
 * Model Companies
 * 
 */
export type Companies = Prisma.CompaniesModel
/**
 * Model JobSkills
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type JobSkills = Prisma.JobSkillsModel
/**
 * Model Jobs
 * 
 */
export type Jobs = Prisma.JobsModel
/**
 * Model MatchResults
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type MatchResults = Prisma.MatchResultsModel
/**
 * Model Roles
 * 
 */
export type Roles = Prisma.RolesModel
/**
 * Model Skills
 * 
 */
export type Skills = Prisma.SkillsModel
/**
 * Model UserBadges
 * 
 */
export type UserBadges = Prisma.UserBadgesModel
/**
 * Model UserEducations
 * 
 */
export type UserEducations = Prisma.UserEducationsModel
/**
 * Model UserSkills
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type UserSkills = Prisma.UserSkillsModel
/**
 * Model Users
 * 
 */
export type Users = Prisma.UsersModel
